### ISSUE TITLE
Duplicated information from ee_models_library.csv

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#289]
## Context
 * Currently, the information contained in the `ee_models_library.csv` (model names, mapping `bbs entity type names <--> spacy entity type names`, ... is duplicated in several places.
 * For instance, it is also found in
   * dvc's `params.yaml`
   * `dvk.lock`
   * in a way, also hardcoded in the entrypoints of `dvc` we 
 * Ideally, we would just like the information to be in one place (e.g. `ee_models_library.csv`) and the others to use that information.

## Actions
 - [ ] Design a code refactoring or some sort of solution (e.g. create extra dvc stage or other) allowing to reduce the duplication of information included in `ee_models_library.csv`.

**Comment by pafonta** [comment]
UPDATE Closing.

The whole logic around `ee_models_library.csv` has been removed in #349.

Besides, the simplification of `params.yaml:eval` (removing the need of `etype_name`) is part of #308.

This issue is then closed.
