### ISSUE TITLE
Define processes for improving NER (extensions + fine-tuning)

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#293]
## Scope

We must define two processes to explain in detail which steps are to be followed to improve the NER system based on user feedback.
For this ticket to be Done, a flowcharts for each of these processes must be produced.

### Process 1: Support a new entity type
We may for instance consider—among others—the following points.
- Relation of new entity type with previous ones (overlapping? subset? ...)
- Collect annotated sentences (how many on average? from how many experts? inter-rater? ...)
- Chose base model to fine tune (SciBERT? scispaCy model? ...)

### Process 2: Correct NER errors
We may for instance consider—among others—the following points.
- How do we deal with errors of type I and type II?
- In which case should we use Rule-Based and in which case should we collect more training samples?

**Comment by pafonta** [comment]
As an inspiration, here is the flowchart from `Prodigy` on NER:
https://prodi.gy/prodigy_flowchart_ner-36f76cffd9cb4ef653a21ee78659d366.pdf

**Comment by EmilieDel** [comment]
Hello @FrancescoCasalegno, is this issue a duplicate of #342 ? Or is there something more to do for this one ?

**Comment by FrancescoCasalegno** [comment]
Duplicate of #342 .
