### ISSUE TITLE
Train NER model for "PATHWAY" using spaCy

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#319]
1. Use frozen backbone corresponding to the BioBERT_NLI_STS_CORD19_v1.
2. Use training set = annotations15_EmmanuelleLogette_2020-09-22_raw9_Pathway.jsonl.

**Note**: it's the same of #318 , just using `spacy` 's 2.0 `spacy train` command instead of 🤗's `transformers` interface.

**Comment by pafonta** [comment]
Closed.

The experiment was done in #328.

It was closed to deploy it for all entities: https://github.com/BlueBrain/Search/pull/328#issuecomment-818929155.
