### ISSUE TITLE
Reduce number of dependencies of bluesearch

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#330]
(See also #326)

In the past we discussed the importance of making optimizing the number of dependencies we need install to be able to use `bluesearch`. 

PR  #326 goes in this direction, but further actions to remove more dependencies are still possible — I would just like to discuss them before implementing them.

### 1. `joblib`
Used only to `dump()` and `load()` models from `sklearn`.
```bash
data_and_models/pipelines/sentence_embedding/train.py:81:            joblib.dump(model, f)
data_and_models/pipelines/sentence_embedding/train.py:93:            joblib.dump(model, f)
src/bluesearch/embedding_models.py:183:        self.model = joblib.load(self.checkpoint_path)
```
#### Options to remove this dependency
1. Use `pickle` instead of `joblib` — it should be possible, although maybe a bit less efficient ([source](https://scikit-learn.org/stable/modules/model_persistence.html#python-specific-serialization)).
2. Stop supporting the `sklearn` models for sentence embedding.

### 2. `scikit-learn`
In `src/` it is only for the confusion matrix, while in `data_and_models` it is used for the cosine similarity and for the 
```bash
data_and_models/pipelines/sentence_embedding/eval.py:31:from sklearn.metrics.pairwise import cosine_similarity
data_and_models/pipelines/sentence_embedding/train.py:28:from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
src/bluesearch/mining/eval.py:584:            data=sklearn.metrics.confusion_matrix(
```
#### Options to remove this dependency
1. If we implement the confusion matrix ourselves (doable, but will be almost a copy-paste of `sklearn`'s code), we can move `scikit-learn` from `install_requires` to `extra_requires`.
2. If we also implement the cosine distance ourselves (trivial)  and if we supporting the `sklearn` models for sentence embedding, we can remove `scikit-learn` altogether.

### 3. `tqdm`
It is only used for `bluesearch.utils.H5` for the methods `load()` and `find_unpopulated_rows()`.
```bash
src/bluesearch/utils.py:308:                iterable = tqdm.tqdm(iterable)
src/bluesearch/utils.py:410:                iterable = tqdm.tqdm(iterable)
```
#### Options to remove this dependency
1. This package is not strictly needed (if `verbose=False` it is not even used at all), so we may just remove `tqdm` and that's it.
2. If we want to provide some logging info to the user, we can write that manually e.g.  add a line `if i%100: print(f"Done {i} iterations")`.

### 4. `matplotlib`
In the `src/` part, it is only used once for plotting the confusion matrix.
```bash
src/bluesearch/mining/eval.py:649:        f, ax = plt.subplots(figsize=(len(e_types_pred) * 0.6, len(e_types_true) * 0.6))
```
#### Options to remove this dependency
1. We could generate the plot of confusion matrix directly in the `eval.py` script. This solution allows to move the dependency to `extra_requires`.
2. We could decide that we do do not want to generate such plots, a `.csv` with the confusion matrix could also be enough. This solution allows to remove the dependency altogether.

### 5. `pdfkit`
In the `src/`, this is only used used to create the PDF reports of the Search widget.
```bash
src/bluesearch/widgets/article_saver.py:301:        pdfkit.from_string(article_report, output_file_path)
src/bluesearch/widgets/search_widget.py:939:            pdfkit.from_string(
```
In fact, this Python package is just a wrapper of the library `wkhtmltopdf`, so to be able to use `pdfkit` one also needs to ensure that the binaries `wkhtmltopdf` are installed and in the current `PATH`. In practice, this point has turned out to be a big issue in the past (see e.g. experience with OOD).

#### Options to remove this dependency
1. Ask users if this feature of generating a report is still a must-have or nice-to-have. If not, drop the dependency.
2. As a compromise, we may generate a `.html` report that can be opened with any browser with a double click—sure, it's less straighforward than a PDF but maybe still fine for the users.

**Comment by pafonta** [comment]
Hello @FrancescoCasalegno,

For `scikit-learn`, please remember you asked to use it in https://github.com/BlueBrain/Search/pull/248#discussion_r601653796.

Therefore, `scikit-learn` couldn't be removed.

**Comment by FrancescoCasalegno** [comment]
### Decisions after discussing with the team
1. `joblib`: drop
2. `scikit-learn`: keep for the moment
3. `tqdm`: drop
4. `matplotlib`: move to `extra_requires`
5. `pdfkit`: ask final confirmation to users and if they accept, drop
