### ISSUE TITLE
Use seqeval for NER model evaluation

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#336]
## 🚀 Feature

We have seen in PR #329 that [`seqeval`](https://github.com/chakki-works/seqeval) is a good framework that implements many metrics for the evaluation of NER models.

We should avoid reinventing the wheel, so we can probably replace most of the code in `bluesearch.mining.eval` with calls to this library. But we must be careful with this, since this change may also impact the scores computed in `data_and_models/pipelines/ner/eval.py`.

## Details
- [x] Investigate whether/why the scores computed using our functions are different from those computed using `seqeval`. Assume that `y_1` and `y_2` are both valid IOB NER annotations: we should e.g. test this for the inter-rater annotations and to evaluate the predictions of our various NER models.
- [x] See if there is any functionality that we have in `bluesearch.mining.eval` but is not implemented in `seqeval`.
- [x] See if there would be any other drawback in using `seqeval`. 
- [x] Change our code to use `seqeval` instead of our custom evaluation functions.

**Comment by jankrepl** [comment]
# Approaches that were considered
* `bluesearch_entity`- uses the `ner_report` from `bluesearch.mining.eval` with mode `entity`
* `bluesearch_token`- uses the `ner_report` from `bluesearch.mining.eval` with mode `token`
* `seqeval_default`- user the `seqeval`'s `classification_report` with default parameters
* `seqeval_IOB1`- user the `seqeval`'s `classification_report` with parameters `mode="strict", scheme=IOB1`
* `seqeval_IOB2` - user the `seqeval`'s `classification_report` with parameters `mode="strict", scheme=IOB2`

# Important points
* The difference between the `seqeval_default` and `seqeval_IOB2` classification report seems to only exist when the predictions are inconsistent (`['I-NP', 'I-NP', 'O']`) (see the README of `seqeval`)
* It seems like our `bluesearch_entity` approach is giving more or less the same results as the `seqeval_default` and `seqeval_IOB2`. See below the evaluation where the predictions are `spacy` models (note that we did not drop punctuation).
![spacy_models](https://user-images.githubusercontent.com/18519371/115397787-c1bef780-a1e6-11eb-9aad-bd873ff372e0.png)


# Should we go for `seqeval`?
IMO not. Why?
* It is not well documented and maintained
* It seems like our internal evaluation gives more or less the same results.
* It does not seem to have an approach similar to our `bluesearch_token`

# Are there any todos?
* `bluesearch_entity` errors out when the predictions are inconsistent. We might want to adjust our implementation to also handle this situation.

**Comment by FrancescoCasalegno** [comment]
Thank you @jankrepl  for running these tests!

I have another few questions based on what I read in their [`README.md`](https://github.com/chakki-works/seqeval#readme) (unfortunately they don't have proper Docs) and other resources online.



#### 1. `IOB1` vs `IOB2`
There are various **alternative and incompatible** annotation formats, so `IOB1` and `IOB2` are two of them. If you are interested, there's a good description of all formats [here].(https://github.com/sighsmile/conlleval/blob/423ac49bc1d6d777a237d0ff9507fccdd9523ee7/conlleval_perl.py#L60-L72).
Anyway, since we have always used `IOB2` for all our annotations, I think it does not makes sense to consider `sequeval_IOB1` values.

#### 2. `default` vs `strict`
It seems that the `default` mode does not mark as error the differences between `IOB1` and `IOB2`—or, equivalently, if one of the two predictions is "inconsistent" (which is in fact equivalent to say that they use a `IOB1` format!).
I don't think we want this, so I would just consider `strict` and ignore `seqeval_default`.

#### 3. `sequeval_IOB2` vs `bluesearch_entity `
According to the definitions, these two should give **exactly** the same results. This is however not the case for `DISEASE`, `ORGANISM`, and `PROTEIN`—which means that either `seqeval` or `bluesearch` has bug here!
@jankrepl can you please find out the reason of this inconsistencies?

#### 4. `entity` vs `token`
Maybe I missed it, but `seqeval` only supports the `entity` evaluation mode, while `bluesearch.mining.eval` has both modalities. @jankrepl can you confirm if you understand the same or instead I missed this feature in `seqeval`?

**Comment by FrancescoCasalegno** [comment]
As an (at least partial) answer to the point **"3. `sequeval_IOB2` vs `bluesearch_entity`"**, the following snipped generates a minimal example of the different behavior of `seqeval` and `bluesearch`. Notice that **the error is on our side!**

#### Code
```python
import pandas as pd
from bluesearch.mining.eval import ner_report as bluesearch_report
from seqeval.metrics import classification_report as seqeval_report
from seqeval.scheme import IOB2

true = ["B-DISEASE", "I-DISEASE", "I-DISEASE"]
pred = ["B-DISEASE", "B-DISEASE", "I-DISEASE"]

print("-"*60 + "\n" + "    BlueSearch report\n" + "-"*60)
print(bluesearch_report(pd.Series(true), pd.Series(pred), mode="entity"))

print("\n")
print("-"*60 + "\n" + "    SeqEval report\n" + "-"*60)
print(seqeval_report([true], [pred], digits=2, mode="strict", scheme=IOB2))
```

#### Output
```bash
------------------------------------------------------------
    BlueSearch report
------------------------------------------------------------
           precision    recall  f1-score   support
   DISEASE      0.50      1.00      0.67         1


------------------------------------------------------------
    SeqEval report
------------------------------------------------------------
              precision    recall  f1-score   support

     DISEASE       0.00      0.00      0.00         1

   micro avg       0.00      0.00      0.00         1
   macro avg       0.00      0.00      0.00         1
weighted avg       0.00      0.00      0.00         1
```

**Comment by EmilieDel** [comment]
Hello @FrancescoCasalegno, 

> Maybe I missed it, but `seqeval` only supports the `entity` evaluation mode, while `bluesearch.mining.eval `has both modalities. @jankrepl can you confirm if you understand the same or instead I missed this feature in `seqeval`?

As I worked partially with @jankrepl on this issue, I can confirm that we did not find any `token` evaluation mode in the `seqeval` package. This is one of the reason why we think it is better to stick to `bluesearch.mining.eval` and forget about `seqeval`. 

> My two cents—I would be in favor of keeping the current behavior. We cannot really say if y_pred is inconsistent or just written with a different format (e.g. IOB1) so unless we add more parameters I would keep it as is.

I agree! Moreover, `spaCy` models are outputting consistent predictions 😄 

> As an (at least partial) answer to the point "3. sequeval_IOB2 vs bluesearch_entity", the following snipped generates a minimal example of the different behavior of seqeval and bluesearch. Notice that the error is on our side!

Really nice finding 🎉
