### ISSUE TITLE
Understand spaCy NER head architecture

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#340]
## Context
While both `huggingface` and `spacy` approaches to NER (see #318 and #319, respectively) use a transformer backbone model, the two approaches differ in the way the structure the head model. In particular `spacy` uses by default the [`TransitionBasedParser`](https://spacy.io/api/architectures#TransitionBasedParser) architecture.

## Actions
 - [ ] Present in a tech talk how this architecture works. Is it still what described in [Lample 2016](https://arxiv.org/pdf/1603.01360.pdf)? If Yes, why do they stick to such an old paper while there are now lots of various approaches in SotA papers? Ask `spacy` devs if needed.
 - [ ] Investigate how/whether one can register and load a head model written in `torch` into `spacy`. Are there examples of that? Ask `spacy` devs if needed.

**Comment by Stannislav** [comment]
Hi @FrancescoCasalegno @pafonta I remember you asked various questions on the spacy forum. Was there anything related to custom pipeline modules or NER among them? Just want to avoid posting duplicate questions :)

**Comment by pafonta** [comment]
Hello @Stannislav !

> Was there anything related to custom pipeline modules or NER among them?

If we are talking about creating our `spaCy pipeline component` or how the `spacy.TransitionBasedParser.v2` architecture works, not on my side.

**Comment by Stannislav** [comment]
I posted a question on the spacy discussion pages

[NER: replacing the TransitionBasedParser ?](https://github.com/explosion/spaCy/discussions/7995)

**Comment by Stannislav** [comment]
Some usefule documentation

- [`EntityRecognizer` pipeline component](https://spacy.io/api/entityrecognizer)
- [`TransitionBasedParser` model](https://spacy.io/api/architectures#parser)
- [Defining custom `thinc` models](https://thinc.ai/docs/usage-models)

**Comment by Stannislav** [comment]
This issue was split into two new issues: #357 + #358
