### ISSUE TITLE
Remove ee_models_library.csv

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#349]
## Context

Once #335 is solved, it is not necessary to have the file `ee_models_library.csv` any more.

Indeed, such file was needed to know which NER model to use in order to extract a given entity type, but we have decided (see also #342) that from now on for each entity type there will be a dedicated NER model stored under ` data_and_models/models/ner_er/model-<entity_type_name>/`.

## Actions
- [x] remove `ee_models_library.csv`
- [x] remove `load_ee_models_library()`
- [x] modify all functions that relied on `ee_models_library.csv` or `load_ee_models_library()`

**Comment by pafonta** [comment]
This issue is related to #289. Maybe solving the current one could solve #289. To be evaluated.

**Comment by pafonta** [comment]
UPDATE Actions

There is also `tests/data/mining/request/ee_models_library.csv` to remove.

**Comment by Stannislav** [comment]
Is #277 going to be affected by this ticket?
