### ISSUE TITLE
Identify open literature sources to create a neuro-scientific literature db

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#353]
- [x] Ask scientists and other about existing internal resources similar to this db
- [x] Identify other sources available online
- [x] Create a Confluence page with details on each possible source (n of papers, n of papers in full-text, format, available metadata, paid options ...)

**Comment by jankrepl** [comment]
Writeup: https://bbpteam.epfl.ch/project/spaces/display/BBS/Database+Creation

**Comment by Stannislav** [comment]
Nice, thanks for the write up.

Maybe we can also check the [CORD-19 paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7251955/) and get inspired by their sources and processes?

**Comment by FrancescoCasalegno** [comment]
Seems good for the moment! 🎉 
Follow-ups are #369 and #370.

@jankrepl please have a look to see if you like how the Confluence page has changed.

**Comment by jankrepl** [comment]
> Seems good for the moment! 🎉
> Follow-ups are #369 and #370.
> 
> @jankrepl please have a look to see if you like how the Confluence page has changed.

Looks amazing! Thank you for the work!
