### ISSUE TITLE
Data versioning, backup and pipeline tracking for SQL databases

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#354]
!This is an exploratory issue.

Questions:
* Given an existing database, what is the recommended way to back it up? Could it be tracked with DVC?
* Does the concept of versioning exist for databases? More specifically, is it possible to add a version tag and then check it out at any point?
* If the database is a result of taking multiple raw sources, preprocessing them and adding them as rows to existing tables would there be any benefits/issues with turning it into a DVC pipeline? See below an example
```text
  * initialize empty tables
  * take raw `data_1`
  * apply `preprocessing_1.sh` to `data_1` to get `preprocessed_data_1`
  * populate the database with `preprocessed_data_1` 
  * take raw `data_2`
  * apply `preprocessing_2.sh` to `data_2` to get `preprocessed_data_2`
  * populate the database with `preprocessed_data_2` 
  * ...
```

**Comment by Stannislav** [comment]
So, an interesting strategy for backing up a MySQL database is described [here](https://jpaulmora.github.io/2020/03/22/how-to-properly-backup-mysql/).

Summary:
- Cron job dumps whole database to binary files using [`mysqldump`](https://dev.mysql.com/doc/mysql-backup-excerpt/8.0/en/using-mysqldump.html) daily/weekly.
- MySQL [binary log](https://dev.mysql.com/doc/refman/8.0/en/binary-log.html) records incremental changes to DB between file backups.

Both strategies are also mentioned in the [official docs](https://dev.mysql.com/doc/mysql-backup-excerpt/8.0/en/backup-methods.html)
