### ISSUE TITLE
Summarize the Transition-Based-Parser Architecture

### ISSUE THREAD

**Issue by Stannislav** [BlueBrain/Search#357]
This ticket is split off from #340

The gloas are
- Understand the transition-based-parser architecture described in [Lample et al.](https://arxiv.org/abs/1603.01360)
- Understand its adaptation to spacy
- Document findings on Confluence

**Comment by Stannislav** [comment]
- Spacy's NER model talk: [YouTube](https://www.youtube.com/watch?v=sqDHBH9IjRU) + [slides](https://github.com/explosion/talks/blob/master/2017-11-02_Practical-and-Effective-Neural-NER.pdf)

**Comment by Stannislav** [comment]
Done. See confluence.

**Comment by Stannislav** [comment]
As discussed in the standup, are you guys happy with the result, or would you like more information?

Writeup: https://bbpteam.epfl.ch/project/spaces/pages/viewpage.action?pageId=45482862#MLTIL(TodayILearned)-Spacy'sDefaultNERModel:TransitionBasedParser

I'm happy:
- [ ] @EmilieDel 
- [ ] @pafonta 
- [ ] @jankrepl 
- [ ] @FrancescoCasalegno 

Once everyone's happy we can close this issue.

**Comment by jankrepl** [comment]
Great job!

**Comment by FrancescoCasalegno** [comment]
@Stannislav  LGTM thanks! I just left a few comments on Confluence, can you have a look when you have time?
