### ISSUE TITLE
Collect information on "License / Legal terms" to download articles

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#370]
- [x] Information on the various kinds of licenses (e.g. the various CC-*) need to be added in a new section of the page created for #353.
- [x] The column "License / Legal terms" of the table created in #353 needs to be filled.
- [x] In particular, it is important to know what are the legal terms to (i) download (ii) re-use (iii) store the papers.

**Comment by EmilieDel** [comment]
Hello! I am not sure how far we need to go with this issue! 

[Here](https://bbpteam.epfl.ch/project/spaces/display/BBS/Database+Creation) are the first findings about license. Changes are mainly under `Licenses and Open Access Info` and `License / Legal Terms` of the table under `Repositories Info`. 
@FrancescoCasalegno, what do you think?

**Comment by FrancescoCasalegno** [comment]
- [ ] @FrancescoCasalegno 
- [ ] @jankrepl 
- [ ] @Stannislav 
- [ ] @pafonta

**Comment by FrancescoCasalegno** [comment]
Great work @EmilieDel thanks!
I left a quick question on Confluence, other than that all good for me!

**Comment by Stannislav** [comment]
Thanks @EmilieDel . I also left a small comment on Confluence.

**Comment by FrancescoCasalegno** [comment]
I think this can be considered Done!
