### ISSUE TITLE
Huggingface tokenizer provides incorrect model_max_length

### ISSUE THREAD

**Issue by EmilieDel** [BlueBrain/Search#385]
## 🐛 Bug description

During the creation of the `mining_cache`, an issue was raised:
```
Article ID: 2951
Traceback (most recent call last):
  File "/raid/users/edelattr/Search/src/bluesearch/database/mining_cache.py", line 146, in work_loop
    self._mine(article_id)
  File "/raid/users/edelattr/Search/src/bluesearch/database/mining_cache.py", line 199, in _mine
    texts=texts, model_entities=self.model, models_relations={}, debug=True
  File "/raid/users/edelattr/Search/src/bluesearch/mining/pipeline.py", line 116, in run_pipeline
    for doc, metadata in docs_gen:
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/language.py", line 1451, in pipe
    for doc, context in zip(docs, contexts):
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/language.py", line 1484, in pipe
    for doc in docs:
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/pipe.pyx", line 53, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/transition_parser.pyx", line 189, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1439, in minibatch
    batch = list(itertools.islice(items, int(batch_size)))
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "spacy/pipeline/pipe.pyx", line 53, in pipe
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy/util.py", line 1484, in _pipe
    yield from proc.pipe(docs, **kwargs)
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/pipeline_component.py", line 204, in pipe
    self.set_annotations(subbatch, self.predict(subbatch))
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/pipeline_component.py", line 220, in predict
    activations = self.model.predict(docs)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/model.py", line 312, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/edelattr/.local/lib/python3.7/site-packages/spacy_transformers/layers/transformer_model.py", line 142, in forward
    tensors, bp_tensors = transformer(wordpieces, is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/model.py", line 288, in __call__
    return self._func(self, X, is_train=is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/layers/pytorchwrapper.py", line 80, in forward
    Ytorch, torch_backprop = model.shims[0](Xtorch, is_train)
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 29, in __call__
    return self.predict(inputs), lambda a: ...
  File "/home/edelattr/.local/lib/python3.7/site-packages/thinc/shims/pytorch.py", line 38, in predict
    outputs = self._model(*inputs.args, **inputs.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 964, in forward
    past_key_values_length=past_key_values_length,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/bert/modeling_bert.py", line 206, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (551) must match the size of tensor b (512) at non-singleton dimension 1
```

This was also found and described on `spacy` github repo: https://github.com/explosion/spaCy/discussions/7393

## To reproduce

1. `dvc pull` last version of `ner_er` models
2. Run this code
```python
from bluesearch.mining import run_pipeline
from bluesearch.sql import retrieve_articles
import spacy

article_ids = [3707,]
all_texts = retrieve_articles(article_ids, bbs_mysql_engine)

spacy_model = spacy.load(path)
for i, row in all_texts.iterrows():
    run_pipeline([(row.text, {"article_id": row.article_id})], spacy_model, {})
```

## Expected behavior

We should find a way to fix the `model_max_length`:
- Either at the tokenizer level
- Either at the spacy `config.cfg` level.

## Environment

Please provide the following information.

 - Blue Brain Search version (use `python -c "import bluesearch; print(bluesearch.__version__)"`): 0.1.3.dev25
 - OS (e.g., Linux): Linux
 - How you installed Blue Brain Search (source, pip, ...): pip
 - Python version (use `python -V`): Python 3.7.5

**Comment by EmilieDel** [comment]
Base code
```python
from bluesearch.mining import run_pipeline
from bluesearch.sql import retrieve_articles
import spacy
import sqlalchemy

article_ids = [3707,]
bbs_mysql_engine = sqlalchemy.create_engine("mysql+pymysql://{user}:{password}@{DB_URL}")
all_texts = retrieve_articles(article_ids, bbs_mysql_engine)

path = "../../data_and_models/models/ner_er/model-chemical/"
spacy_model = spacy.load(path)
for i, row in all_texts.iterrows():
    run_pipeline([(row.text, {"article_id": row.article_id})], spacy_model, {})
```
gives this error (because tokenizer maximum length is too high):
```
RuntimeError: The size of tensor a (641) must match the size of tensor b (512) at non-singleton dimension 1
```

How to handle this problem ?
🚫 - not working
✔️ - working 

1. 🚫 **SpaCy side**: Adding the `model_max_length` into `spacy_model.config` in place 
Line of code to add just before the for-loop:
```python
spacy_model.config['components']['transformer']['model']['tokenizer_config']['model_max_length'] = 512
```

2. ✔️ **SpaCy side**: Adding one line in the `config.cfg` of the model
Before: 
```
[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "../../models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/"
```
After:
```
[components.transformer.model]
@architectures = "spacy-transformers.TransformerModel.v1"
name = "../../models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/"
tokenizer_config = {"model_max_length": 512}
```

3. ✔️ **SpaCy side**: Loading `tokenizer` of the models and adding this parameter `model_max_length` to 512 (inspired by [explosion/spaCy#7393](https://github.com/explosion/spaCy/discussions/7393))
```python
from transformers import AutoTokenizer
name = "../../data_and_models/models/ner_er/model-organism/transformer/model/"
tokenizer = AutoTokenizer.from_pretrained(name)
tokenizer.init_kwargs["model_max_length"] = 512
tokenizer.save_pretrained(name)
```

4. 🚫 **Transformers model side**: Loading `tokenizer` of the `sentence_embedding` embedding pipeline (`data_and_models/models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/`) and train `spacy` model.
```python
from transformers import AutoTokenizer, AutoModel
name = "data_and_models/models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/"
tokenizer = AutoTokenizer.from_pretrained(name)
tokenizer.init_kwargs["model_max_length"] = 512
tokenizer.save_pretrained(name)
```

5. (?) **Transformers model side**: Add `max_model_input_sizes` parameter in the `config.json` of the model `clagator/biobert_v1.1_pubmed_nli_sts`
Inspiration from `huggingface.tokenizer` [documentation](https://huggingface.co/transformers/main_classes/tokenizer.html):
> model_max_length (int, optional) – The maximum length (in number of tokens) for the inputs to the transformer model. When the tokenizer is loaded with from_pretrained(), this will be set to the value stored for the associated model in max_model_input_sizes (see above). If no value is provided, will default to VERY_LARGE_INTEGER (int(1e30)).

**Comment by pafonta** [comment]
Hello @EmilieDel !

> @pafonta I would like to have your opinion about this to decide on the best way to tackle this issue!

I had a look. To me, the best way is the following one:

> ✔️ **SpaCy side**: Adding one line in the `config.cfg` of the model
>
> Before:
> ```
> [components.transformer.model]
> @architectures = "spacy-transformers.TransformerModel.v1"
> name = "../../models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/"
> ```
> 
> After:
> ```
> [components.transformer.model]
> @architectures = "spacy-transformers.TransformerModel.v1"
> name = "../../models/sentence_embedding/biobert_nli_sts_cord19_v1/0_Transformer/"
> tokenizer_config = {"model_max_length": 512}
> ```

This is the most readable way IMO. Besides, this is consistent with the behaviour from `transformers`:

http://github.com/huggingface/transformers/blob/6989264963d1f8871404889243d2f15de198ee42/src/transformers/tokenization_utils_base.py#L1756

**Comment by pafonta** [comment]
By the way, we would need to it both on:
- [ ] `models/ner/` and `models/ner_er/` and then `dvc push`.
- [ ] pipelines/ner/dvc.yaml and then `git push`.

The question is how DVC will behave if we do this.

But anyway we can re-launch `dvc repro` in `pipelines/ner/` over night to have a clean slate.

❓ What do you think @EmilieDel?

**Comment by EmilieDel** [comment]
Thanks a lot for the feedback @pafonta. 

Just to be sure to be on the same page, the steps should be: 
1. [ ] Change `data_and_models/pipelines/ner/config.cfg` by adding the new line (and add a comment in the first line of the file to explain this change)
2. [ ] Relaunch `dvc`
3. [ ] `dvc push` and `git push`

Do you agree @pafonta ?

**Comment by pafonta** [comment]
Yes, @EmilieDel: edit `pipelines/ner/config.cfg`, `dvc repro`, `dvc push`, `git push`.

I thouk you are right, that would be easier to just re-do `dvc repro`.
