### ISSUE TITLE
RTD doc is failing

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/Search#387]
## 🐛 Bug description

The docs badge on the README shows that RTD fails to build the documentation.

## To reproduce

One could have a look at the build logs here:
https://readthedocs.org/projects/blue-brain-search/builds/

## Expected behavior

The docs badge on the README should show that RTD succeeds to build the documentation.

## Environment

The master branch on GitHub.

## Additional context

It seems that the cause is from #301.

The PR removed `mysqlclient` in `INSTALL_REQUIRES` but forgot to remove these lines:
https://github.com/BlueBrain/Search/blob/de86792d5260c78ced8f3ade35282e132aa391cc/setup.py#L74-L76

**Comment by pafonta** [comment]
Is the compilation passing on RTD now?

**Comment by Stannislav** [comment]
I don't remember - how do we trigger the RTD builds?

**Comment by jankrepl** [comment]
> I don't remember - how do we trigger the RTD builds?

I think  @FrancescoCasalegno needs to trigger a build for this branch within the RTD web interface.
