### ISSUE TITLE
🚀 Release v0.2.0

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#394]
The [milestone for releasing `v0.2.0`](https://github.com/BlueBrain/Search/milestone/1) is complete.

## Actions
- [x] Re-run all DVC stuff.
- [x] Add new tag `v0.2.0`.
- [ ] Merge into `master`.
- [ ] Check that RTD successfully builds a new `stable` version of the `docs`.
- [ ] Upload new tag on PyPI.

**Comment by pafonta** [comment]
>     * [x]  Check that RTD successfully builds a new `stable` version of the `docs`.

It does: https://readthedocs.org/projects/blue-brain-search/builds/14247657/.

>     * [ ]  Upload new tag on PyPI.

Done: https://pypi.org/project/bluesearch/0.2.0/.
