### ISSUE TITLE
Identify the topic of PMC papers

### ISSUE THREAD

**Issue by Stannislav** [BlueBrain/Search#408]
## 🚀 Feature

PMC data is sorted by journal, e.g. (see `/raid/projects/bbs/pmc`):
```text
Zool_Scr
 Zoomorphology
 Zoonoses_-_Infections_Affecting_Humans_and_Animals
 Zoonoses_Public_Health
'Zoonosi_e_sanit&#x000e0;_pubblica'
 Zoonotic_Viruses_in_Northern_Eurasia
 Zoosyst_Evol
 Zoo_Talk
 Zootaxa
 Zorgvisie
 Zorgvisie_tech
 Zorg_Welz
 Z_Orthop_Unfall
 Z_Politikwiss
 Z_Psychodrama_Soziom
 Z_Psychol
 Z_Rheumatol
 Zuchter
'Zur_Relevanz_der_F&#x000fc;rsorge_in_Geschichte_und_Gegenwart'
 ZVersWiss
 Z_Vgl_Polit_Wiss
 Zwischen_Methodenpluralismus_und_Datenhandel
 Zygon
 Zygote
```
- which of those are relevant to us? (Neuroscience)
- how do we identify the relavant ones?
   - tag in files?
   - by journal?
   - using ML?
- can we determine the topic before downloading?  

## Motivation

Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.

## Pitch

A clear description of what you want to happen.

## Alternatives

Think about any alternative solutions or features that could be used.
Then, write here a clear list of alternatives.

## Additional context
Add any other screenshot, context, or information about the problem here.

**Comment by FrancescoCasalegno** [comment]
## Actions
Note: This is a first tentative of detailing the scope. Currently we know little about this, the scope may be clarified and rediscussed within the team, as more is learned.
- [ ] Investigate if papers and/or journals have any tag or metadata that allows a first, easy determination of the field. E.g. if "neuroscience" or "neurobiology" is in the list of tags, we keep the paper/journal, else we drop it. 
Note that we may also need to look to other resources outside of the downloadable PMC papers themselves, in order to find such kind of information.
➡️ If we can find these tags/metadata, open PR to implement this rule-based logic for inclusion.
- [ ] If we cannot find these tags, or if that approach gives only unsatisfying results, then investigate if we can develop/use a model (rule-based or ML-based) to determine the topic. [LDA](https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation) could be an idea, but it's unsupervised so it's not clear if it can help identifying papers related to keywords we like. Otherwise we could do paper classification, but may require many labelled data.
➡️ Try to see what are the various possible solutions. If there is an easy one to implement, let's try that one.

**Comment by EmilieDel** [comment]
First findings:

### Broad Subject Terms for Indexed Journal
- Useful link: https://journal-reports.nlm.nih.gov/broad-subjects/
- BST are assigned by National Library of Medicine to MEDLINE journals 
- About 120 BST (valid MeSH headings)
- Interesting terms for us: neurology, brain, psychophysiology (?), neurosurgery (?)
- Request on NLM Catalog: Neurology[st] OR Brain[st] OR Psychophysiology[st] (st for subject term)

### Medical Subject Headings (MeSH) 
- Useful link: https://www.nlm.nih.gov/mesh/meshhome.html
- From nlm website:  
> NLM's Medical Subject Headings controlled vocabulary of biomedical terms that is used to describe the subject of each journal article in MEDLINE. MeSH contains more than 23,000 terms and is updated annually to reflect changes in medicine and medical terminology. MeSH terms are arranged hierarchically by subject categories with more specific terms arranged beneath broader terms. Entrez allows you to view this hierarchy and select terms for searching in the MeSH database.
- Tree View of the MeSH: https://meshb.nlm.nih.gov/treeView
- There is “Neurosciences” term: https://meshb.nlm.nih.gov/record/ui?ui=D009488, id D009488 / Tree structures: [H01.158.610]
- There are MeSH Major Topic (= MeSH terms that is one of the main topics discussed in the article), MeSH Terms and MeSH Subheadings (SH)
- MeSH Subheadings are used with MeSH terms to help describe more completely a particular aspect of a subject. For example, the drug therapy of asthma is displayed as asthma/drug therapy.
- It is possible to find MeSH of an article using EFetch. However, you need to use pubmed database (implying you also need ):
    ```python
    import requests

    from defusedxml import ElementTree

   url = f"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id={pubmed_id}&retmode=xml"
    
    response = requests.get(url)
    if response.status_code == 200:
        content = ElementTree.fromstring(response.content.decode())
    else:
        raise ValueError("The request did not work")
    
    meshs = []
    mesh_heading_list = content.findall(".//MeshHeadingList")
    for mesh_heading in mesh_heading_list:
        for mesh in list(mesh_heading):
            descriptor_name = None
            qualifiers_name = []
            
            for info in list(mesh):
                if info.tag == "DescriptorName":
                    descriptor_name = info.text
                if info.tag == "QualifierName":
                    qualifiers_name.append(info.text)
            
            if len(qualifiers_name) > 0 and descriptor_name is not None:
                for qualifier in qualifiers_name:
                    meshs.append(f"{descriptor_name} / {qualifier}")
    ```


### ESummary 
- Useful link: https://dataguide.nlm.nih.gov/eutilities/utilities.html#esummary
- returns document summaries for a list of unique identifiers (UIDs).
- Can potential gives all IDs of an article (PubMed, PMC, DOI, …)
- Ex: “https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&id=22368089&retmode=json”

**Comment by EmilieDel** [comment]
### NLM Catalog 
It seems it is possible to have topic of journal through NLM catalog. From what I understand, the `oa_bulk` download of PMC has the given structure:
```
journal1/
- PMCXXX1.nxlm
- PMCXXX2.nxlm
journal2/
....
```
The folder name is the NLM Title abbreviation (`[ta]`).
 
Here is the code I used to extract journal topic. The request is retrieving the equivalent to this link: https://www.ncbi.nlm.nih.gov/nlmcatalog/101698646
```python
def get_mesh(nlm_ta):
    # Using the NLM title abbreviation to do the request
    nlm_ta_api = "+".join(nlm_ta.split(" "))
    url = f"https://www.ncbi.nlm.nih.gov/nlmcatalog/?term={nlm_ta_api}%5Bta%5D&report=xml&format=xml"

    # The request
    response = requests.get(url)
    if not response.ok:
        raise ValueError("The request did not work")
        
    # The content of the response is a fake xml, so we convert is to a real one
    text = response.content.decode().replace("<pre>", "").replace("</pre>", "").replace("\n", "").replace("&lt;", "<").replace("&gt;", ">")
    try:
        et = ElementTree.fromstring(text)
    except ElementTree.ParseError:
        raise ElementTree.ParseError("The parsing did not work")
    
    # There are two ways to extract journal topic (through MeSH) in the given xml
    # 1. with NLMCatalogRecord
    mesh_from_nlm = et.findall("./NLMCatalogRecord/MeshHeadingList/MeshHeading/DescriptorName")
    mesh_from_nlm = {d.text for d in mesh_from_nlm}
    
    # 2. with JrXml
    mesh_from_jrxml = et.findall("./JrXml/Serial/MeshHeadingList/MeshHeading/DescriptorName")
    mesh_from_jrxml = {d.text for d in mesh_from_jrxml}
    
    return mesh_from_nlm, mesh_from_jrxml
```

Some useful informations:
-  The request can be done with other information than the title abbreviation (see documentation of NLM Catalog). I used that one in the current case because of the `oa_bulk` structure. 
- Out of the 15869 folders (=journals) we have on DGX, it was possible to extract MeSH for 7712 of them (=49%). 
- It is not possible to do the query for several journal at the same time 
- It seems the MeSH extracted from both solution (`NLMCatalogRecord` & `JrXml`) are the same
- Out of the 7712 journal containing at least one MeSH, here is the repartition:

   | Number of MeSH | Number of Journals | 
   | -- | -- | 
   | 1 | 3012 |
   | 2 | 2398 |
   | 3 | 1352 |
   | 4 | 481 |
   | 5 | 132 |
   | 6 | 41 |
   | 7 | 8 |
   | 8 | 2 |
   | 9 | 1 |
   | 10 | 1 | 

- In total, there are 2378 different MeSH. One can find some terms like `Neurosciences`,  `Neurosurgical Procedures`, `Neuroendocrinology`, `Neuropsychiatry `, ...

**Comment by Stannislav** [comment]
# Which Journal/Article IDs do PMC XML Files Contain?

Here's part of the `PMC5474141.nxml` file:
```xml
<article xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML"
         article-type="research-article"><?properties open_access?><?properties manuscript?>
    <front>
        <journal-meta>
            <journal-id journal-id-type="nlm-journal-id">101299742</journal-id>
            <journal-id journal-id-type="pubmed-jr-id">35518</journal-id>
            <journal-id journal-id-type="nlm-ta">Mucosal Immunol</journal-id>
            <journal-id journal-id-type="iso-abbrev">Mucosal Immunol</journal-id>
            <journal-title-group>
                <journal-title>Mucosal immunology</journal-title>
            </journal-title-group>
            <issn pub-type="ppub">1933-0219</issn>
            <issn pub-type="epub">1935-3456</issn>
        </journal-meta>
        <article-meta>
            <article-id pub-id-type="pmid">28051083</article-id>
            <article-id pub-id-type="pmc">5474141</article-id>
            <article-id pub-id-type="doi">10.1038/mi.2016.116</article-id>
            <article-id pub-id-type="manuscript">NIHMS830841</article-id>
            ...
```
You can see that it contains various journal and article IDs. Which and how many different IDs can be found in 1.340.946 PMC XML files that we have?

![journal-id-type](https://user-images.githubusercontent.com/8017698/131314297-b76597da-c9aa-4e67-85a2-e027307fd47a.png)
![pub-id-type](https://user-images.githubusercontent.com/8017698/131314305-1b4adb78-d94c-4aef-9896-e5c213f7ba96.png)

**Comment by Stannislav** [comment]
# Focus on NLM Catalog / `nlm-journal-id`

Take as an example `PMC5474141.nxml`, it contains the `nlm-journal-id` tag:
```xml
<journal-id journal-id-type="nlm-journal-id">101299742</journal-id>
```

The NLM Catalog entry for this ID can be found here: https://www.ncbi.nlm.nih.gov/nlmcatalog/101299742

In the upper left corner there is a drop-down list that says "Full".
After clicking and selecting XML one can get an XML version of the
record. URL: https://www.ncbi.nlm.nih.gov/nlmcatalog/101299742?report=xml&format=text
However, it's actually the XML source rendered as HTML with all tags are escaped 🤦🏻.

It's also possible to access the record using E-Utils. Docs
- E-Utils docs: https://www.ncbi.nlm.nih.gov/books/NBK25501
- EFetch part of the docs: https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EFetch

so we get the following EFetch URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nlmcatalog&id=101299742&retmode=xml

But the result does not contain all the records found in the first approach 🤦🏻🤦🏻.
In particular, the broad subject terms are missing...

So, in conclusion, we have the following options
- Use EFetch to only extract the MeSH entries, but not the broad subject terms
- Investigate if there is a way in EFetch to also get the broad subject terms (probably not...)
- Use the NLM Catalog way, remove the "pre" tags and unescape the tags.

Note also that apparently it's possible to fetch multiple records at the same time. Maybe we should make use of this

There a difference between the two methods though:
    
**The NCBI Website**
- Always returns one single NLM record
- Contains additional information including the broad topic (in `JrXml`)
- Doesn't seem to contain all records (e.g. 101299742 yes, but 101675946 no)
- Has the following structure

```
- NCBICatalogRecord
  - NLMCatalogRecord
  - JrXml
```

**EFetch**
- Can return multiple NLM records
- Doesn't have the broad topic information included
- Has the following structure

```
- NLMCatalogRecordSet
  - NLMCatalogRecord
  - NLMCatalogRecord
  - NLMCatalogRecord
  - ...
```

NCBI Record: https://www.ncbi.nlm.nih.gov/nlmcatalog/101299742

The corresponding (escaped) XML record: https://www.ncbi.nlm.nih.gov/nlmcatalog/101299742?report=xml&format=text

EFetch with two IDs: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nlmcatalog&retmode=xml&id=101299742,101675946

MeSH headings can also be found in the PubMed database - investigate!
Example: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml&id=35518

E-Utilities Quick Start: https://www.ncbi.nlm.nih.gov/books/NBK25500/

Entrez help: https://www.ncbi.nlm.nih.gov/books/NBK3837/

Entrez Programming Utilities Help: https://www.ncbi.nlm.nih.gov/books/NBK25501/

Entrez databases: https://www.ncbi.nlm.nih.gov/books/NBK3837/#EntrezHelp.The_Entrez_Databases

EFetch docs: https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EFetch

NLMCatalogRecordSet XML Elements: https://www.nlm.nih.gov/bsd/licensee/catrecordxml_element_desc2.html

Some data extraction lib in Java: Textractor: https://pubmed.ncbi.nlm.nih.gov/20819864/
It's interesting because they seem to implement the broad journal topic extraction: https://chagall.med.cornell.edu/textractor/api/textractor/xml/pubmed/xml/class-use/BroadJournalHeadingList.html

**Comment by Stannislav** [comment]
# Code for using the NLM Catalog

<details>
<summary>Fetching from the NLM Catalog website</summary>

Implementation
```python
def fetch_ncbi_record(nlm_id):
    # Fetch the XML content
    url = f"https://www.ncbi.nlm.nih.gov/nlmcatalog/{nlm_id}?report=xml"
    response = requests.get(url)
    response.raise_for_status()
    
    # Unescape the tags
    text = (
        response.text
        .replace("<pre>", "")
        .replace("</pre>", "")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
    )
    
    # Convert response to ElementTree
    file = StringIO(text)
    et = ElementTree.parse(file)
    file.close()
    
    return et
```
Test
```python
et_ncbi_record = fetch_ncbi_record("101299742")

print(et_ncbi_record.getroot().tag)  
for e in et_ncbi_record.getroot():
    print(f"  {e.tag}")
```
Output
```text
NCBICatalogRecord
  NLMCatalogRecord
  JrXml
```
</details>

<details>
<summary>Fetching using EFetch</summary>

Implementation
```python
def fetch_nlm_records(nlm_ids):
    """
    Structure of the returned XML:
    - NLMCatalogRecordSet
      - NLMCatalogRecord
      - NLMCatalogRecord
      - NLMCatalogRecord
    """
    # Fetch the XML content
    unique_nlm_ids = set(nlm_ids)
    base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
    url = f"{base_url}/efetch.fcgi?db=nlmcatalog&retmode=xml&id={','.join(unique_nlm_ids)}"
    response = requests.get(url)
    response.raise_for_status()
    
    # Convert response to ElementTree
    file = StringIO(response.text)
    et = ElementTree.parse(file)
    file.close()
    
    # Check if all records were found
    if len(et.getroot()) != len(unique_nlm_ids):
        ids_found = set([e.text for e in et.findall("./NLMCatalogRecord/NlmUniqueID")])
        logger.warning(f"Not all NLM IDs were found. Missing IDs: {unique_nlm_ids - ids_found}")
    
    return et
```
Test
```python
et_nlm_records = fetch_nlm_records(["101299742", "101675946"])

print(et_nlm_records.getroot().tag)
for e in et_nlm_records.getroot():
    print(f"  {e.tag} {e.find('./NlmUniqueID').text}")
```
Output
```text
NLMCatalogRecordSet
  NLMCatalogRecord 101675946
  NLMCatalogRecord 101299742
```
</details>

<details>
<summary> Extract MeSH Records and Broad Topics</summary>

MeSH Records
```python
def extract_mesh_records(nlm_catalog_record):
    """
    <MeshHeadingList>
    Required: No
    Repeatable: No
    Attributes: (none)
    Child elements:
    
        <MeshHeading>
        Required: Yes
        Repeatable: Yes
        Attributes: (none)
        Child elements:

            <DescriptorName>
            Required: Yes
            Repeatable: No
            Attributes: MajorTopicYN, Type, UI
            <QualifierName>
            Required: No
            Repeatable: No
            Attributes: MajorTopicYN, UI

    Source: https://www.nlm.nih.gov/bsd/licensee/catrecordxml_element_desc2.html#MeshHeadingList
    """
    tag = nlm_catalog_record.tag
    if tag != "NLMCatalogRecord":
        raise ValueError(f"Expected the tag to be 'NLMCatalogRecord' but got {tag}.")

    yn = {"Y": True, "N": False}
    records = []
    for mesh_heading in nlm_catalog_record.findall("./MeshHeadingList/MeshHeading"):
        descriptor_name = mesh_heading.find("./DescriptorName")
        if descriptor_name is None:
            logger.warning("DescriptorName element missing - record skipped")
            continue
        
        records.append({
            "uri": mesh_heading.get("URI"),
            "descriptor_name": descriptor_name.text,
            "major_topic": descriptor_name.get("MajorTopicYN") == "Y",
            "qualifiers": [
                {
                    "qualifier_name": qualifier_name.text,
                    "major_topic": qualifier_name.get("MajorTopicYN") == "Y"
                }
                for qualifier_name in mesh_heading.findall("./QualifierName")
            ],
        })
    return records
```

Broad Topics
```python
def extract_broad_topics(jr_xml):
    tag = jr_xml.tag
    if tag != "JrXml":
        raise ValueError(f"Expected the tag to be 'JrXml' but got {tag}.")
    records = [
        element.text
        for element in jr_xml.findall("./Serial/BroadJournalHeadingList/BroadJournalHeading")
    ]
    return records
```
</details>

## Examples
### Fetching several NLM records: MeSH only
```python
>>> et_nlm_records = fetch_nlm_records(["101299742", "101675946"])
>>> mesh_records = {}
>>> for nlm_record in et_nlm_records.getroot():
>>>     nlm_id = extract_nlm_id(nlm_record)
>>>     mesh_record = extract_mesh_records(nlm_record)
>>>     mesh_records[nlm_id] = mesh_record
>>> 
>>> mesh_records
{'101675946': [],
 '101299742': [{'uri': 'https://id.nlm.nih.gov/mesh/D018928',
   'descriptor_name': 'Immunity, Mucosal',
   'major_topic': True,
   'qualifiers': []}]}
```

### Fetching a single NCBI record: MeSH + Broad Topic
```python
>>> et_ncbi_record = fetch_ncbi_record("101299742")
>>> et_ncbi_record.getroot().get("ID")
'101299742'
>>> extract_mesh_records(et_ncbi_record.find("./NLMCatalogRecord"))
[{'uri': 'https://id.nlm.nih.gov/mesh/D018928',
  'descriptor_name': 'Immunity, Mucosal',
  'major_topic': True,
  'qualifiers': []}]
>>> extract_broad_topics(et_ncbi_record.find("./JrXml"))
['Allergy and Immunology']
```

**Comment by FrancescoCasalegno** [comment]
Follow-up: https://github.com/BlueBrain/Search/issues/439
