### ISSUE TITLE
Generate Unique IDs for Database Data

### ISSUE THREAD

**Issue by Stannislav** [BlueBrain/Search#409]
## 🚀 Feature
- Find a way to assign an ID to e.g. an article (file?)
- Something like the PMC-ID? But that works for everything
- Imprtant to have a good ID in order to incrementally fill the database
- Problem in the past: same article, but from different sources

=> Brainstorm different solutions
- Some kind of hash?
- Article embedding + clustering?
- Pre-defined IDs like PMC?
- ...

=> Really important to have a good solution

## Motivation

Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.

## Pitch

A clear description of what you want to happen.

## Alternatives

Think about any alternative solutions or features that could be used.
Then, write here a clear list of alternatives.

## Additional context
Add any other screenshot, context, or information about the problem here.

**Comment by FrancescoCasalegno** [comment]
## Actions
- [ ] Have a look at how CORD-19 authors did to generate a unique ID for each paper (see paper [here](https://arxiv.org/abs/2004.10706)).
- [ ] Try to implement a similar logic for our database in a dedicated PR.

**Comment by pafonta** [comment]
>  Have a look at how CORD-19 authors did to generate a unique ID for each paper (see paper here).

The process is to generate an identifier for each group of papers sharing the same value for an existing identifier (e.g. DOI, PubMed ID, ...). If a paper in one of these groups has also a different value for one of the identifiers, it is put in another group. This approach is common when dealing with data from multiple sources. The process is described in section 2.2.
