### ISSUE TITLE
Select useful keys into XML paragraphs

### ISSUE THREAD

**Issue by EmilieDel** [BlueBrain/Search#427]
## 🚀 Feature

Currently, we keep every key contained into a paragraph parsed by `PubmedXMLParser`. For example:
<p>Some text can be in <italic> different </italic> style.</p>.
Some of them are simple text styling (like `italic`, `bold`). In this case, the text inside might be kept.

However, some others might not be useful or need a refactoring. See for example, @Stannislav's comment: 

_LaTeX code / formulas. See PMC7122938 for an example. The formula R_0 >= 1 leads to this block in the XML files:_
```xml
<inline-formula id="IEq3">
    <alternatives>
        <tex-math id="M5">\documentclass[12pt]{minimal}
            \usepackage{amsmath}
            \usepackage{wasysym}
            \usepackage{amsfonts}
            \usepackage{amssymb}
            \usepackage{amsbsy}
            \usepackage{mathrsfs}
            \usepackage{upgreek}
            \setlength{\oddsidemargin}{-69pt}
            \begin{document}$$ R_{0} \ge 1 $$\end{document}
        </tex-math>
        <mml:math id="M6">
            <mml:mrow>
                <mml:msub>
                    <mml:mi>R</mml:mi>
                    <mml:mn>0</mml:mn>
                </mml:msub>
                <mml:mo>&#x02265;</mml:mo>
                <mml:mn>1</mml:mn>
            </mml:mrow>
        </mml:math>
        <inline-graphic xlink:href="466534_1_En_109_Chapter_IEq3.gif"/>
    </alternatives>
</inline-formula>
```
_so what to do with this? Maybe just throw away? Maybe replace it with some generic placeholder token like usually done in ML?_

It could be nice to:
[ ] Analyze the type of key found into paragraphs' papers
[ ] Decide the one we want to keep/remove
[ ] Implement the desired solution

**Comment by Stannislav** [comment]
Just illustrate the problem again. Given this part that was copied verbatim from one of the XML files:
```python
xml_str = r"""
<article xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink">
<p>Two equilibriums points were found, disease free and endemic equilibrium, and basic reproduction ratio <inline-formula id="IEq1"><alternatives><tex-math id="M1">\documentclass[12pt]{minimal}
				\usepackage{amsmath}
				\usepackage{wasysym} 
				\usepackage{amsfonts} 
				\usepackage{amssymb} 
				\usepackage{amsbsy}
				\usepackage{mathrsfs}
				\usepackage{upgreek}
				\setlength{\oddsidemargin}{-69pt}
				\begin{document}$$ R_{0} $$\end{document}</tex-math><mml:math id="M2"><mml:msub><mml:mi>R</mml:mi><mml:mn>0</mml:mn></mml:msub></mml:math><inline-graphic xlink:href="466534_1_En_109_Chapter_IEq1.gif"/></alternatives></inline-formula> was also calculated by the use of next generation matrix.</p></article>
"""
et = ElementTree.fromstring(xml_str)
```
In the `PubmedXMLParser` parser we do something [like this](https://github.com/BlueBrain/Search/blob/a37bfca303728e3a8cfe94abff533584b44e04ea/src/bluesearch/database/article.py#L231-L247)
```python
print("".join(paragraph.itertext()))
```
which gives
```
Two equilibriums points were found, disease free and endemic equilibrium, and basic reproduction ratio \documentclass[12pt]{minimal}
				\usepackage{amsmath}
				\usepackage{wasysym} 
				\usepackage{amsfonts} 
				\usepackage{amssymb} 
				\usepackage{amsbsy}
				\usepackage{mathrsfs}
				\usepackage{upgreek}
				\setlength{\oddsidemargin}{-69pt}
				\begin{document}$$ R_{0} $$\end{document}R0 was also calculated by the use of next generation matrix.
```
Problems:
- LaTeX code from the inner `<inline-formula>` tag.
- Newlines present (while it seems the paragraph text never has new lines)

We'll probably need to handle the different tags within paragraphs separately (like the `<inline-formula>` one above) and depending on the tag decide what to do with its contents.
- Do we need the formulas (and maths in general) for attribute extraction? Could be tough to parse
- There are simple text formatting tags like `<italic>hello</italic>` for which we should just drop the tags and keep the text.

Here's a prototype:
```python
def tag_to_str(tag):
    # Do something more clever depending on the tag
    return subtag.tag.upper()

parts = [paragraph.text]
for subtag in paragraph:
    parts.append(tag_to_str(subtag))
    parts.append(subtag.tail)  # don't forget the text after the tag
print("".join(parts))
```
which gives
```
Two equilibriums points were found, disease free and endemic equilibrium, and basic reproduction ratio INLINE-FORMULA was also calculated by the use of next generation matrix.
```

**Comment by Stannislav** [comment]
We also need to check if we don't have a duplication issue for nested paragraphs.

Example
```python
xml_str = r"<article><p>One <p>Two</p> <p>Three</p> </p></article>"
et = ElementTree.fromstring(xml_str)
for paragraph in et.findall(".//p"):
    print("".join(paragraph.itertext()))
```
output:
```
One Two Three 
Two
Three
```
We get "Two" and "Three" two times. That's because `et.findall(".//p")` is a glob and `paragraph.itertext()` recursively visits all child elements too.

**Comment by Stannislav** [comment]
Using this small script I parsed all XML files we have and checked which tags we can expect to find in paragraphs:
```python
#!/usr/bin/env python
import html
import pathlib
from collections import Counter
from pprint import pprint
from xml.etree import ElementTree

from tqdm import tqdm

def count_p_subtags(et):
    """Find all sub-tags within paragraphs of an element tree."""
    tags = Counter()
    for p in et.findall(".//p"):
        tags.update(child.tag for child in p)

    return tags


print("Collecting all NXML files...")
xml_files = list(pathlib.Path("pmc").rglob("*.nxml"))
print(f"{len(xml_files):,d} files found.")
print("Start parsing and counting")
tag_counts = Counter()
for path in tqdm(xml_files, ncols=80):
    et = ElementTree.parse(path)
    tag_counts.update(count_p_subtags(et))

print("Counts of all tags found inside paragraphs:")
pprint(tag_counts.most_common())
```
which gives
```
Collecting all NXML files...
1,340,936 files found.
Start parsing and counting   
100%|████████████████████████████████| 1340936/1340936 [51:08<00:00, 437.06it/s]
Counts of all tags found inside paragraphs:
[('xref', 60339251),                
 ('italic', 32686526),   
 ('sup', 15877780),
 ('sub', 9796718),
 ('bold', 7183035),
 ('inline-formula', 1462973),
 ('ext-link', 1382712),
 ('fig', 840142),
 ('list', 724159),
 ('table-wrap', 489548),
 ('disp-formula', 466554),
 ('styled-content', 424011),
 ('sc', 422245),
 ('funding-source', 198130),
 ('underline', 168388),
 ('disp-quote', 103104),
 ('inline-graphic', 100079),
 ('supplementary-material', 96697),
 ('email', 66186),
 ('graphic', 65722),
 ('named-content', 65318),
 ('uri', 62626),
 ('{http://www.w3.org/1998/Math/MathML}math', 57604),
 ('boxed-text', 53905),
 ('mixed-citation', 49122),
 ('award-id', 34840),
 ('inline-supplementary-material', 31252),
 ('monospace', 29610),
 ('statement', 14967),
 ('def-list', 13290),
 ('related-article', 12151),
 ('private-char', 8498),
 ('disp-formula-group', 7192),
 ('fn', 5946),
 ('element-citation', 4103),
 ('media', 3019),
 ('preformat', 1699),
 ('chem-struct', 1588),
 ('speech', 1244),
 ('grant-sponsor', 1136),
 ('citation', 1043),
 ('overline', 865),
 ('sans-serif', 865),
 ('strike', 787),
 ('roman', 718),
 ('abbrev', 704),
 ('grant-num', 662),
 ('array', 438),
 ('code', 429),
 ('chem-struct-wrap', 368),
 ('target', 267),
 ('related-object', 209),
 ('tex-math', 206),
 ('index-term', 176),
 ('fig-group', 151),
 ('verse-group', 122),
 ('hr', 60),
 ('font', 26),
 ('table-wrap-group', 24),
 ('x', 18),
 ('overline-start', 9),
 ('overline-end', 9),
 ('address', 1)]
```
Thoughts:
- A lot of different tags, probably can't handle all one-by-one
- Probably can focus on a few important and frequent cases and have some default strategy for the rest (either skip, replace by `"PLACEHOLDER"`, or just greedily convert to text as before...)
- Some elements can just be converted to text as usual, e.g. `<bold>` and `<italic>`
- `<fig>`, `<fig-group>` etc. - what to do? Can we skip them because we handle figure/table captions separately?
- `<inline-formula>` and `<disp-formula>` are really common, need proper handling
- There's also `<list>` which contains bullet-pointed text, so probably need to extract it properly
- `<xref>` are citations, I've seen both `... as described in [<xref>12</xref>].` and `... some statement<sup><xref>12</xref></sup>`, so if for `<xref>` we just extract the text and parse `<sub>` to `^` then the examples above would parse to `... as described in [12].` and `... some statement^12` respectively. I'm just slightly worried that things like `"statement^12"` would cause problems on the level of NLP as it appears as one word. But maybe this can be addressed on the level of the NLP parser/tokenizer.
