### ISSUE TITLE
Create unique `article_id` column when `bbs_database add` is called

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#448]
## 🚀 Feature

In https://github.com/BlueBrain/Search/pull/418 we introduced utilities to compute a unique `article_id` for each article ingested into our database. 

We now need to integrate this into `bbs_database add` command, so that the `article` table will have a `PRIMARY KEY` (and therefore `UNIQUE`, `NOT NULL`) column `article_id` filled as new papers are ingested.

This implies also extracting identifiers when parsing the article. See also [these lines](https://github.com/BlueBrain/Search/blob/b9e515a63592e992e31420f99b5424a703831909/src/bluesearch/entrypoint/database/add.py#L71-L72) from https://github.com/BlueBrain/Search/pull/440.

**Comment by jankrepl** [comment]
We agreed during our standup that generating the identifier should be a responsibility of the `ArticleParser` subclasses.
