### ISSUE TITLE
Parse lists and tables in XML files correctly

### ISSUE THREAD

**Issue by Stannislav** [BlueBrain/Search#449]
In #437 a custom parsing of XML tags was introduced. At the moment only a subset of tags are properly processed, the rest go through a default fall-back processing which just extracts all the text.

While the default handling is good enough for most cases it appears that other tags like `list` and `table-wrap` need to be handled in a better way.

# To do
- Identify tags for which the processing needs to be imporved (see the big table in #437)
- Cross-check on the real data from the open-access dataset
- Implement a handling for those tags
- Post the updated tag implementation table here.

# Details
Another 2 tags that I think are important but at the same time relatively feasible to handle are `list` and `table-wrap`. For `list` in particular, I think we can pretty much just extract the text, but maybe we need to double check to make sure nothing weird happens.

Maybe you can create one issue for each of those two?

_Originally posted by @FrancescoCasalegno in https://github.com/BlueBrain/Search/pull/437#discussion_r710043549_

**Comment by pafonta** [comment]
⚠️  Currently, the elements of lists are duplicated by the parser (`PMCXMLParser`)!

➡️  The literature database contains duplicated sentences from this parsing issue.

<details>
  <summary>details</summary>

Example XML of an article with a list in a paragraph:

```xml
<article>
    <body>
        <p>
            <list list-type="bullet">
                <list-item>
                    <p>List item 1.</p>
                </list-item>
                <list-item>
                    <p>List item 2.</p>
                </list-item>
            </list>
        </p>
    </body>
</article>
```

Parsing of such article file (article.xml):

```python
from bluesearch.database.article import PMCXMLParser

parser = PMCXMLParser("article.xml")
for paragraph in parser.paragraphs:
  print(paragraph)
```

Duplicated outputs:

```
('', 'List item 1.\n                List item 2.')
('', 'List item 1.')
('', 'List item 2.')
```

</details>

**Comment by pafonta** [comment]
Note: This issue depends on #447. Indeed, the processing of tags is impacted by the decision taken on #447.

**Comment by pafonta** [comment]
### `<table-wrap>`

This is a very complex element to parse if not with a specific goal in mind

For example, one would need to handle column spanning ([@colspan](https://jats.nlm.nih.gov/archiving/tag-library/1.2/attribute/colspan.html)): _how many column widths this cell will span_.

If the parsing is done naively, the output would have the following format (example, not exhaustive):

```
caption
column headers
row headers
cell values
```

That might not be informative for users nor useful for training or embedding in the case of language models.

➡️  Maybe there is no specific additional parsing to do for tables at the moment, as the table caption is handled.

**Comment by pafonta** [comment]
Actually, there are a lot of other elements than lists and tables that could be parsed the same way. However, there is a lot of complexity in handling each case individually and without a common strategy. Furthermore, this strategy should be generic to handle the non hierarchical repartition of elements to parse. For example, `<list>` could be in `<body>` but also in `<p>` or also `<p>` could be in `<list>`.

❓  To move forward with the ticket, I think we need to decide the following things:

1. Should we parse what is outside the narrative (figures, tables, codes, ...)?

2. If yes, which part should be parse?
  a. The common content (captions, ...)?
  b. The specific content (graphics, cells, codes, ...)?

3. If yes, where should the parsed content be stored?
  a. In dedicated `Article` properties (e.g. `Article.figures`, `Article.tables`, `Article.codes`, ...)?
  b. In `Article.paragraphs`? In place (where it is in the XML)? At the end of `Article.paragraphs`?

➡️  After answering the above questions, we will know if something needs to be changed or improved.

⚠️  In any case, the bug described here should be fixed: https://github.com/BlueBrain/Search/issues/449#issuecomment-959739587.

**Comment by Stannislav** [comment]
> handle the non hierarchical repartition of elements to parse

Just to mention that there's already some recursive tag handling in `PMCXMLParser` where `_element_to_str` recurses to itself throught `_inner_text`.

**Comment by pafonta** [comment]
> > handle the non hierarchical repartition of elements to parse
> 
> Just to mention that there's already some recursive tag handling in `PMCXMLParser` where `_element_to_str` recurses to itself throught `_inner_text`.

Indeed. I think this is actually where the bug described in https://github.com/BlueBrain/Search/issues/449#issuecomment-959739587 is happening.

**Comment by pafonta** [comment]
As decided by the team, the follow-up on https://github.com/BlueBrain/Search/issues/449#issuecomment-961230794 is just to fix the bug discovered in https://github.com/BlueBrain/Search/issues/449#issuecomment-959739587.

To avoid having to go through the context of this issue, a dedicated issue as been created for fixing this bug: https://github.com/BlueBrain/Search/issues/496.
