### ISSUE TITLE
`Article` missing defaults

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#466]
Currently, to construct an `Article` one needs to provide all 8 of the parameters. However, the type hints suggest that
* `pubmed_id`
* `pmc_id`
* `doi`
* `uid`

are optional.

https://github.com/BlueBrain/Search/blob/a494a99d89943a38944ba4314a255368f00dece1/src/bluesearch/database/article.py#L522-L525

We should actually honor what the type hints say and set the defaults to `None`. That is

```python
 pubmed_id: Optional[str] = None
...
```

 Additionally, why does `mypy` allow this?

**Comment by jankrepl** [comment]
> Doesn't it just mean that the values can be `None` as you call the constructor?
> 
> Anyway, meaningful defaults can for sure be necessary where appropriate

Sure. However, then one needs to have calls like these

```python
foo("a", "b", None, None, None)
```
which just does not look right (highly subjective).

Also, I am very much used to seeing `foo: Optional[bar] = None` (as opposed to `foo: Optional[bar]`) in other peoples' code.

**Comment by Stannislav** [comment]
Yep, yep,  totally agree. Let's maybe check at the same time if the nones are handled correctly.

**Comment by pafonta** [comment]
Hello @jankrepl and @Stannislav. I am looking at this issue.

Haven't we said that an `Article` should only be created by calling its `parse` method?

In this case, optional fields actually receive `None` without any action from the caller.

Indeed, the methods in the base class `ArticleParser` return None by default. Example for `doi`:

https://github.com/BlueBrain/Search/blob/431c9b3beb734a434e356ad3a3f1f17f4feb37c4/src/bluesearch/database/article.py#L103-L112

➡️  So, should we close this issue?
