### ISSUE TITLE
`article_id` starts with 4 leading zeros

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#467]
# Description
It seems like ~all~ the first 20 articles in our MariaDB have an `article_id` that stars with 4 leading zeros. However, the MD5 hash that we are using should create 32 character hashes without any clear patterns.

# How do I reproduce it?
```mysql
select article_id from articles limit 10;
```

```
| article_id                       |
+----------------------------------+
| 000016eee4379007954c9a4d0b6aad48 |
| 00002287fc54f7c95752d1d48e535135 |
| 0000249eca32b76ae1bbfffabb00ec70 |
| 00004237495461c7722aec94ef4dbd7b |
| 000047b84edbae5e2d0041f260cc3d00 |
| 0000493e64c1b5ed888274b81664f7ea |
| 00004dfa6ca36cfd9e563a3b3c78f50d |
| 000051cbd84e8807a148619ca6f889d4 |
| 00005e10532597366222ebb33a0b2337 |
| 00006dc708c409f58c0fdf939c1eb67e |
+----------------------------------+
```

# Ideas
* Double check that this is not caused by the MariaDB shell (that just simply pads the output)
* I tried to reproduce the behavior with `sqlite`, however, I was not able to. Maybe it is related to `MySQL/MariaDB`
* One quick way to test this is to add some logic to `tests/integration/test_bbs_database.py`

**Comment by pafonta** [comment]
Hello @jankrepl,

I had a look. The function `generate_uid` gives the same `article_uid` on my computer as on the server and in MariaDB.

<details>
  <summary>experiment</summary>

An example from MariaDB:

```
> select pubmed_id, pmc_id, doi from articles where article_id = '0000249eca32b76ae1bbfffabb00ec70';
+-----------+---------+--------------------------+
| pubmed_id | pmc_id  | doi                      |
+-----------+---------+--------------------------+
| 28761416  | 5514858 | 10.4103/1673-5374.208547 |
+-----------+---------+--------------------------+
```

Here is how article_uid is computed at the moment:

https://github.com/BlueBrain/Search/blob/fc823da37572a42d1c963345ddb11b389903a6d6/src/bluesearch/database/article.py#L124

The output for the example above:

```python
>>> generate_uid(("28761416", "5514858", "10.4103/1673-5374.208547"))
'0000249eca32b76ae1bbfffabb00ec70'
```

➡️  The two article_uid are identical.

</details>

> I tried to reproduce the behavior with `sqlite`, however, I was not able to. Maybe it is related to `MySQL/MariaDB`

So I guess there is something else to the story. Indeed, it seems the two previous findings are in contradiction.

Have you tried to reproduce the behaviour on the server or on your computer? Indeed, hardware might be involved.
