### ISSUE TITLE
Download the content of `arXiv/q-bio`

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#473]
## Actions

- [x] **Download `arXiv/q-bio`** – On Kaggle ([here](https://www.kaggle.com/Cornell-University/arxiv)) you can download the whole `arXiv`. Is it possible to automatically only extract the papers from `arXiv/q-bio` out of it?
~- [ ] **Parse and Load**  – First, convert `PDF` into `TEI XML` (#374). Then, parse and  `TEI XML` (#373).~
~- [ ] **More Parsers?** – So far we assumed that articles from `arXiv/q-bio` will only be available in PDF format. But we know that in many cases the `TeX` source is available, and possibly even other source types like `HTML` could be used on `arXiv` ([source](https://arxiv.org/format/2109.14558)). Which percentage of our sources has a `TeX` source file available? Which percentage has `HTML` source available? If these numbers are high, consider creating an Issue to implement a `TexParser` / `HtmlParser` etc.~

**Comment by FrancescoCasalegno** [comment]
Hi guys, have a look and feel free to comment / criticize what mentioned above!

Check your box ✅  once you're convinced that this ticket is Done.

- [ ] @Stannislav 
- [ ] @EmilieDel 
- [ ] @jankrepl 
- [ ] @pafonta

**Comment by pafonta** [comment]
Thank you for doing this.

I guess this issue should be renamed `"Download arXiv/q-bio"` to be considered `done` and avoid confusions, isn't it?

There are several directories in `processed-arxiv-q-bio`. All papers not in the subdirectory `q-bio` are papers from before 2007-03 which weren't in the `q-bio` category, aren't they?

What would be the rationale behing keeping all versions of a paper?

**Comment by Stannislav** [comment]
Read through this, looks good for me and makes sense!

**Comment by jankrepl** [comment]
Looks good to me:) Thank you for doing this. Looking at the issue description, it is very ambitious because it also wants as to do the actual parsing and loading in the database. I guess we can do this internally without tracking it here, right? @FrancescoCasalegno

**Comment by EmilieDel** [comment]
Thanks for the great summary! Looks good to me :)

**Comment by FrancescoCasalegno** [comment]
@pafonta 

>  All papers not in the subdirectory q-bio are papers from before 2007-03 which weren't in the q-bio category, aren't they?

Yes, exactly!

> What would be the rationale behing keeping all versions of a paper?

I wasn't quite sure about what to do when there's more than one version. Based on your remark, I have now modified the Python so that only the latest version is taken into account.

<details>
  <summary> Example </summary>

```bash
$ ll /raid/projects/bbs/arxiv-downloads/fulltext-dataset/processed-arxiv-q-bio-backup/arxiv/pdf/0712/0712.0462v*

0712.0462v1.pdf
0712.0462v2.pdf
0712.0462v3.pdf
0712.0462v4.pdf
0712.0462v5.pdf
0712.0462v6.pdf
0712.0462v7.pdf
0712.0462v8.pdf
0712.0462v9.pdf
0712.0462v10.pdf
0712.0462v11.pdf
0712.0462v12.pdf
0712.0462v13.pdf
0712.0462v14.pdf
0712.0462v15.pdf
0712.0462v16.pdf
0712.0462v17.pdf
0712.0462v18.pdf
0712.0462v19.pdf
0712.0462v20.pdf
0712.0462v21.pdf
0712.0462v22.pdf
0712.0462v23.pdf
0712.0462v24.pdf
0712.0462v25.pdf

$ ll /raid/projects/bbs/arxiv-downloads/fulltext-dataset/processed-arxiv-q-bio/arxiv/pdf/0712/0712.0462v*

0712.0462v25.pdf
```
</details>

**Comment by pafonta** [comment]
@FrancescoCasalegno 

Great, thanks for the clarifications. Checking my box in https://github.com/BlueBrain/Search/issues/473#issuecomment-958156627.
