### ISSUE TITLE
Evaluate alternatives to MariaDB (and RDBMS)

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#499]
1. Answer following questions.
      - [ ] Estimate number of articles in the `articles` table + number of rows in the `sentences` table (neuroscience articles only).
             _Note_: If this number is large, then MariaDB is not suitable.
      - [x] Analyze which actions (`INSERT`, `SELECT`, `UPDATE`, ...) we are expected performing on the `sentences` table. 
      E.g. do we need to filter by xxx ... (is it a `FULLTEXT` search? is it a filter on a indexed/indexable column)?
            _Note_: We may want to consider NoSQL alternatives to the current RDBMS architecture.
2. Discuss and complete migration from MariaDB to Postgres.
      - [x] Make changes in the code.
      - [ ] Complete migration to new Postgres database.

**Comment by FrancescoCasalegno** [comment]
The results of https://github.com/BlueBrain/Search/issues/503 are needed to address the following point of this Issue:
> Estimate number of articles in the articles table + number of rows in the sentences table (neuroscience articles only).

**Comment by jankrepl** [comment]
See below a list of SQL queries that were heavily inspired by our code.

You can just create a `db.sqlite` exactly like `pytest tests/integration/test_bbs_database.py -k "sqlite"` does and then run

```bash
sqlite3 db.sqlite '.read queries.sql'   
```

The `queries.sql`
```sql
.output /dev/null

-- Simple row count articles
SELECT count(*) FROM articles;

-- Simple row count sentences
SELECT count(*) FROM sentences;

-- Primary key lookup articles
SELECT title
FROM articles
WHERE article_id = '546896bc3f413e796bbea4d084dc4746';

-- Primary key lookup sentences
SELECT text FROM sentences WHERE sentence_id = 22;

-- Primary key lookup many articles
SELECT title
FROM articles
WHERE article_id
    IN ('546896bc3f413e796bbea4d084dc4746', 'bd8c3ef147501fab67a1f75d99c4327c');

-- Primary key lookup many sentences
SELECT text
FROM sentences
WHERE sentence_id
    IN (10, 15, 19);

-- Getting all sentence ids and article ids
SELECT
    sentence_id,
    article_id
FROM sentences;

-- Retrieve the 10th paragraph of article bd8c3ef147501fab67a1f75d99c4327c
SELECT text
FROM sentences
WHERE paragraph_pos_in_article = 10
    AND article_id = 'bd8c3ef147501fab67a1f75d99c4327c'
ORDER BY sentence_pos_in_paragraph ASC;

-- Retrieve text of an entire article
SELECT text
FROM sentences
WHERE article_id = 'bd8c3ef147501fab67a1f75d99c4327c'
ORDER BY paragraph_pos_in_article ASC, sentence_pos_in_paragraph ASC;

-- Article filtering - date range
SELECT article_id
FROM articles
WHERE publish_time
    BETWEEN '2010-01-01'
    AND '2015-12-31';

-- Article filtering - published in a journal
SELECT article_id
FROM articles
WHERE journal IS NOT NULL;

-- Article filtering - is in English
SELECT article_id
FROM articles
WHERE is_english = 1;

-- Sentence filtering - containing text
SELECT
    sentence_id,
    text
FROM sentences
WHERE text LIKE '%cell%';

-- Sentence filtering - not containing text
SELECT
    sentence_id,
    text
FROM sentences
WHERE text NOT LIKE '%data%';

-- Full blown example 1
SELECT sentence_id
FROM sentences
WHERE
    article_id IN (
        SELECT article_id
        FROM articles
        WHERE publish_time
            BETWEEN '2010-01-01' AND '2020-12-31'
            AND journal IS NOT NULL
    )
    AND sentence_id IN (1, 2, 3, 4, 5)
    AND text NOT LIKE '%virus%'
    AND text NOT LIKE '%disease%';

.output
.print 'DONE'
```

**Comment by jankrepl** [comment]
Could you please review?

- [ ] @pafonta 
- [ ] @EmilieDel 
- [ ] @FrancescoCasalegno 
- [ ] @Stannislav

**Comment by Stannislav** [comment]
Nice, thanks for the compilation. I guess we can use this command file to test the PostgreSQL server?

**Comment by DriesVerachtert** [comment]
@jankrepl I've got a question about the 3 last queries "Sentence filtering - containing text", "Sentence filtering - not containing text" and "Full blown example 1": do you expect to use only full words in the LIKE "%something%" part? Or should any substring of a word work? I'm asking because if only words with stemming is acceptable, then certain postgresql optimizations with tsearch2 could be used.

If rather any substring of a word should be supported: is a minimal length of 3 letters acceptable? Then a different type of optimizations could be used based on trigrams.
