### ISSUE TITLE
Identify topic of PubMed papers

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#503]
In https://github.com/BlueBrain/Search/issues/464 we found a way to generate a list of topics of interest and relative `MeSH` ids, and we collected statistics on the topic of the various PMC papers we downloaded.

The goal of this Issue is to collect statistics on the topics of the PubMed papers we downloaded, using the list of topics obtained in  https://github.com/BlueBrain/Search/issues/464.

**Comment by pafonta** [comment]
The counting of papers on specific topics is done by the code [here](https://github.com/BlueBrain/Search/issues/464#issuecomment-949373873).

The `MeSH` terms from the table [here](https://github.com/BlueBrain/Search/issues/464#issuecomment-948796351) and their children are collected with the code [here](https://gist.github.com/pafonta/d33a0d5d849932f8ceab8b711d995497#gistcomment-3965575).

These additional `MeSH` terms (`mesh_names`) could be added to the original ones (`int_meshes`) from the table [here](https://github.com/BlueBrain/Search/issues/464#issuecomment-940086676) with:

```python
topics = set(int_meshes) | mesh_names
```

(`int_meshes` is coming from [here](https://github.com/BlueBrain/Search/issues/464#issuecomment-949373873))

**Comment by pafonta** [comment]
## Statistics

➡️  `5.68 millions` papers - `18 %` of `PubMed` - match the topics from #464.

Details:

articles | count | ratio
-- | --: | --:
total | 31,850,051 | 100 %
without MeSH terms | 4,528,811 | 14 %
with matching MeSH terms | 5,680,706 | 18 %
with other MeSH terms | 21,640,534 | 68 %

(code [here](https://gist.github.com/pafonta/37762f56e8c1879569bca64901d0a000#gistcomment-3968062) and [here](https://github.com/BlueBrain/Search/issues/503#issuecomment-971678163))

**Comment by pafonta** [comment]
Before closing this issue:

As usual, please check your box to confirm you have reviewed the information above:

- [ ] @FrancescoCasalegno 
- [ ] @EmilieDel 
- [ ] @jankrepl 
- [ ] @Stannislav

**Comment by jankrepl** [comment]
Looks good to me! I am wondering about the best way how to to keep the code at one place. I mean gists and github issues are nice but we would like to eventually make it a part of the source code.

**Comment by EmilieDel** [comment]
Interesting result! Thanks for doing this.

**Comment by pafonta** [comment]
Closing the issue to reflect the moving to Done yesterday.

**Comment by EmilieDel** [comment]
Just a small note:
It could be nice to check if it is possible to identify some `MeSH` directly from the journal of the paper. It could maybe help reduce the number of articles without any MeSH identified.

**Comment by pafonta** [comment]
@EmilieDel 

> if it is possible to identify some `MeSH` directly from the journal of the paper

Do you think what was done for `PMC` on this side could be done for `PubMed`?

**Comment by EmilieDel** [comment]
I think something similar can be done yes :)
