### ISSUE TITLE
Implement `bbs_database download --source=pmc`

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#511]
- In https://github.com/BlueBrain/Search/issues/360 we have seen how we can bulk download articles from `PMC-OA` using TFP.
- We now need to implement a command line to support `bbs_database download --source=pmc`.
- There is a set of points that should however be clarified before we do this.
   - On top of the `Open Access` (`OA`) subset, we should now also be able to download the `Author Manuscript Dataset`, which contains “accepted author manuscripts that have been collected under a funder policy in PMC” and therefore “they are available in XML and plain text for text mining purposes”.
   So, instead of talking about `PMC-OA`, probably from now on we should just talk about `PMC` and by that mean both `PMC-OA` and `PMC-Author Manuscript Dataset`.
   - PMC now supports both [download from a FTP server](https://www.ncbi.nlm.nih.gov/labs/pmc/tools/ftp/) and [download from AWS Cloud](https://www.ncbi.nlm.nih.gov/labs/pmc/tools/pmcaws/).
   But in the past, there was only one FTP Server, and the structure was different.
   Which server should we use to download the articles?
   - Should we download from Amazon Cloud, do we need to pay or is the service free?
- The new PMC server (both FTP and Amazon Cloud?) store the articles by year and month, so it is possible to only download papers uploaded to PMC on certain dates.
- The command should support a `--from-month=YYYY-MM` option to let users download all and only those articles that were uploaded to PMC after a give month of a given year.

**Comment by FrancescoCasalegno** [comment]
@EmilieDel @pafonta maybe you can look together into this?

**Comment by EmilieDel** [comment]
### First findings
#### 1. AWS service 
- Useful link: https://www.ncbi.nlm.nih.gov/pmc/tools/pmcaws/
- There is no need for an AWS account
- It is free
- `PMC Open Access` and `Author manuscript` are accessible through this service
- The structure is the following: 
```shell
|_ txt/
   |_ all/
       individual plain text files for each author manuscript, named PMC[accession_id].txt, e.g. PMC1249490.txt
   |_ metadata/
      |_ csv/
         author_manuscript.filelist.csv
      |_ txt/
         author_manuscript.filelist.txt
|_ xml/
   |_ all/
       individual XML files for each author manuscript, named PMC[accession_id].xml, e.g. PMC1043859.xml
   |_ metadata/
      |_ csv/
         author_manuscript.filelist.csv
      |_ txt/
         author_manuscript.filelist.txt
```
- You then need to read csv files and then retrieve the PMC file needed ?
- Not clear how to use the AWS service from python scripts
### 2. FTP server
- `PMC Open Access` and `Author manuscript` are accessible through this service
- The structure is the following (from https://ftp.ncbi.nlm.nih.gov/pub/) - seems easy for the retrieval from a certain date.
```shell
pmc/ 
    manuscript/ 
        txt/
        xml/
             author_manuscript_xml.PMC00[1-8]xxxxxx.baseline.2021-05-26.filelist.csv # Baseline
             author_manuscript_xml.PMC00[1-8]xxxxxx.baseline.2021-05-26.filelist.txt  # Baseline
             author_manuscript_xml.PMC00[1-8]xxxxxx.baseline.2021-05-26.tar.gz  # Baseline
             author_manuscript_xml.incr.2021-05-27.filelist.csv # Daily Incremental Addition
             author_manuscript_xml.incr.2021-05-27.filelist.txt # Daily Incremental Addition
             author_manuscript_xml.incr.2021-05-27.tar.gz # Daily Incremental Addition   
    oa_bulk/
        oa_comm/   # same for oa_noncomm/
           txt/
           xml/
              oa_comm_xml.PMC008xxxxxx.baseline.2021-09-16.filelist.csv # Baseline
              oa_comm_xml.PMC008xxxxxx.baseline.2021-09-16.filelist.txt # Baseline
              oa_comm_xml.PMC008xxxxxx.baseline.2021-09-16.tar.gz  # Baseline
              oa_comm_xml.incr.2021-09-17.filelist.csv # Daily Incremental Addition
              oa_comm_xml.incr.2021-09-17.filelist.txt # Daily Incremental Addition
              oa_comm_xml.incr.2021-09-17.tar.gz # Daily Incremental Addition
    oa_package/
```

#### Note
PMC Open Access has a page for developers (https://www.ncbi.nlm.nih.gov/pmc/tools/developers/)
There is one question: `How to maintain a local copy of the PMC Open Access ?`
Here is the link to the response:
- https://www.ncbi.nlm.nih.gov/pmc/tools/maintain-oa-subset/
- https://www.ncbi.nlm.nih.gov/pmc/tools/oa-service/
For that, one can use the service `https://www.ncbi.nlm.nih.gov/pmc/utils/oa/oa.fcgi` and get all the records updated on or after a specified date for example.
