### ISSUE TITLE
Define output format for `bbs_database topic extract`

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#518]
## Context
- The various literature archives we use to download papers (`PubMed`, `PMC`, `arXiv`, ...)  include a lot of papers that are not related to NeuroScience.
- It would be hard to manage a literature database that includes all sources, so we need to identify the topic of each article to then be able to filter out those that are not of interest.
- Notice that more advanced filtering (e.g. consider only papers in English, or published after a certain date, ...) can anyway be done afterwords, and possibly even at runtime. Here we are just trying to identify the topics of each article.

## Scope
- Before we implement a `bbs_database topic extract` command (dedicated Issues will be created), the present Issue requires to define the output format of such a command.
  - Should we use `CSV`, `JSONL`, or other?
  - How do we deal with the fact that a single file (typically this is the case of `PubMed`) may contain more than one article? 
  - If CSV, which columns do we want in our schema? E.g. `source, filename, article_n_in_file, topic_info`?
  - How do we handle the fact that the topic info depend on the source? E.g. for `PMC` we have a list of MeSH topics relative to the journal and a list of MeSH topics relative to the article, while for `arXiv` we have a list of arXiv topics relative to the article etc.

**Comment by FrancescoCasalegno** [comment]
I think CSV may not be the most suitable to this use case, because:
- sets of topics are more naturally interpreted as lists and tabular format is not very list-friendly
- we have attributes that depend on the source, e.g. if an article is not from `arXiv` all topics lists will be empty
- the filed `article_n_in_file` is only relevant for `PubMed`, and in all other cases it will be a `0`


What about a JSONL like this?

<details>
  <summary>Example of an element of the JSONL representing a PubMed paper</summary>
  
  ```json
  {
    "filename": "/gpfs/.../proj115/downloads/pubmed/some_file.txt", 
    "article_n_in_file":  1,
    "source": "pubmed"
    "mesh_topics_article": 
      [
        "A08", 
        "C10.10", 
        "E04.525"
      ],
    "mesh_topics_journal":
      [
        "A08", 
        "C10"
      ]
  }
  ```
</details>


<details>
  <summary>Example of an element of the JSONL representing an arXiv paper</summary>
  
  ```json
  {
    "filename": "/gpfs/.../proj115/downloads/arXiv/some_file.pdf", 
    "source": "arxiv"
    "arxiv_topics": 
      [
        "cs.CV", 
        "math.DS"
      ]
  }
  ```
</details>

**Comment by FrancescoCasalegno** [comment]
What do you guys think of the above proposal?
The source-specific fields can then be defined when we implement the various `bbs_database topic extract --source=xxx` commands in the relative Issues, but at least with this Issue we can agree on the overall structure of the output.
- [ ] @pafonta 
- [ ] @EmilieDel 
- [ ] @jankrepl 
- [ ] @Stannislav

**Comment by pafonta** [comment]
To harmonize the data model and therefore the processing logic, the JSONL could also looks like this:

```json
{
  "source": "<source name>",
  "path": "<file path>(:<element in file>)?",
  "topics_article": ["<topic name>+"],
  ("topics_journal": ["<topic name>+"],)?
}
```

Then, depending on the value of `source`, the processing logic will know:
- if `(:<element in file>)?` is expected or not,
- if `("topics_journal": ["<topic name>+"],)?` is expected or not,
- to which reference list of topic names match the content of `topics_article`.

**Comment by FrancescoCasalegno** [comment]
Hi @pafonta thanks for the feedback!

I like the idea of harmonizing the data model, I think it's a good principle to follow.

> depending on the value of source, the processing logic will know [...] to which reference list of topic names match the content of topics_article.

The problem is that we could have (not now, maybe in the future) different ways to infer the topic of a given publication.
So what about using a nested structure like the following?

```json
{
    "source": "<source name>",
    "path": "<file path>(:<element in file>)?",
    "topics": 
        "article":
             "MeSH": ["<topic name>+"],
             "MAG": ["<topic name>+"]
         "journal":
             "MeSH": ["<topic name>+"],
}
```

**Comment by pafonta** [comment]
Hello @FrancescoCasalegno,

> we could have (not now, maybe in the future) different ways to infer the topic of a given publication

In this case, the hierarchy `topics` > `article | journal` > `MeSH | other` looks good to me.

**Comment by jankrepl** [comment]
Thank you for the writeup and suggestions. See below questions/comments


1. Do you want us to introduce another nesting level in the CLI ( i.e. allowing for "subsubcommand"s)? Would the `topic` "subcommand" contain more "subsubcommands" in the future?
```bash
bbs_database
    add
    convert-pdf
    download
    init
    parse
    topic
        extract

```
2. I guess the JSONL you proposed [here](https://github.com/BlueBrain/Search/issues/518#issuecomment-984471596) is reasonable.

**Comment by FrancescoCasalegno** [comment]
Hi @jankrepl 

> Do you want us to introduce another nesting level in the CLI 

Yeah I am not too fond of this approach either :/  

Do you have any better suggestions for how to handle that?
Consider that we have decided to split (i) the topics extraction from (ii) the topics checking (i.e. verify if the topics are compatible with a topic of choice).

**Comment by jankrepl** [comment]
> Hi @jankrepl
> 
> > Do you want us to introduce another nesting level in the CLI
> 
> Yeah I am not too fond of this approach either :/
> 
> Do you have any better suggestions for how to handle that? Consider that we have decided to split (i) the topics extraction from (ii) the topics checking (i.e. verify if the topics are compatible with a topic of choice).

IMO as long as we are intending to add more "subsubcommands" then it is completely fine:) If not we could always flatten the hierarchy by `bbs_database topic extract` -> `bbs_database topic-extract` (similarly to what we did with `convert-pdf` I guess).

**Comment by EmilieDel** [comment]
I agree with @jankrepl's concerns and I find the last proposal of JSON structure great. If we need, we can also consider adding `metadata` key containing specific information depending on the source.

**Comment by FrancescoCasalegno** [comment]
Ok perfect, so by taking into account all suggestions, let's close this issue with the following.

1. The command will be `bbs_database topic-extract --source=xxx`.
2. The output will be a JSONL file with the following structure:
    ```json
    {
      "source": "<source name>",
      "path": "<file path>(:<element in file>)?",
      "topics": {
          "article":  {
               "MeSH": ["topic1", "topic2"],
               "MAG": ["topic3"]
           },
           "journal": {
               "MeSH": ["topic4", "topic5", "topic6"]
           }
      }
      "metadata": {
        " any-other-info "
      }
    }
    ```
    Notice that:
    - The keys (e.g. `MeSH`, `arXiv`, `MAG`, ...) and the values of `.topics.article` and `.topics.journal` will depend on the `source`.
    - The content of `.metadata` is still to be determined, but it will anyway depend on the `source`.

**Comment by EmilieDel** [comment]
Maybe we can think about putting `element_in_file` into `metadata` as it is specific to `pubmed` source ?
