### ISSUE TITLE
Deal with a deprecation warning coming from `responses=0.17.0`

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#543]
## 🐛 Bug description
I manually triggered a CI run on `master` https://github.com/BlueBrain/Search/actions/runs/1681998905 and it failed.

It seems to be because of the brand new `responses=0.17.0` (https://pypi.org/project/responses/#history). It seems like some of its functionality we use inside of `bluesearch` is going to be deprecated. Note that we are turning all warnings into errors when running unit tests.

https://github.com/BlueBrain/Search/blob/195aebe6962f975974617d670761aaffa6237fb4/tox.ini#L140-L141

**Comment by jankrepl** [comment]
Actually, the fact that the `DeprecationWarning` is raised is raised appears to be a bug inside of the `responses==0.17.0`. For more details see https://github.com/getsentry/responses/issues/464


Potential solutions
* Temporarily pin the `responses` package via `<0.17.0` and wait until a new version with a fix is released
* Manually pass `match_querystring=None` whenever using `add_callback`(as done here https://github.com/pretix/pretix/commit/8ae4304c7d864c61f5536d6c6e49015957728ea6)
* Temporarily ignore all depracation warnings coming from `responses`and wait until a new version with a fix is released

**Comment by FrancescoCasalegno** [comment]
Hi @jankrepl ,

Thanks for the analysis of the problem!

From what the authors of `responses` replied in https://github.com/getsentry/responses/issues/464#issuecomment-1010088535 I have the feeling that until `1.0.0` we may not have a fix to be released, so I would exclude solution `1.` and `3.`.

On the other hand, `2.` is what they recommend to do again in https://github.com/getsentry/responses/issues/464#issuecomment-1010088535. The impact should on our code should also be reasonable (16 lines of code to add in total).

So I would go with `2.`! 👍
