### ISSUE TITLE
`tests/integration/test_bbs_database.py::test_bbs_database[postgres]` fails randomly

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#547]
# Description
See below a list of runs where it failed.
* https://github.com/BlueBrain/Search/actions/runs/1687864091/attempts/1
* https://github.com/BlueBrain/Search/actions/runs/1678055422

Unfortunately, it seems to be random and most of the time it passes.

**Comment by jankrepl** [comment]
Just brainstorming: We have seen random test fails in the CI before and the reason was out of memory problems.

**Comment by Stannislav** [comment]
With out of memory the CI got killed instantly. These ones actually run to the end, so I suspect it might be something different.

**Comment by Stannislav** [comment]
In the logs I see the PostgreSQL error code `57P03`, which according to [the docs](https://www.postgresql.org/docs/current/errcodes-appendix.html) means "Cannot connect now". The error message in the logs is "the database system is starting up".

So maybe we're trying to run commands before the database has finished initialising?

**Comment by jankrepl** [comment]
> In the logs I see the PostgreSQL error code `57P03`, which according to [the docs](https://www.postgresql.org/docs/current/errcodes-appendix.html) means "Cannot connect now". The error message in the logs is "the database system is starting up".
> 
> So maybe we're trying to run commands before the database has finished initialising?

Yeh! I guess the problematic code is here
https://github.com/BlueBrain/Search/blob/d41611ad516e05b2fe28007659b4f33f3d6ce1a1/tests/integration/test_bbs_database.py#L101-L116

My guess is that it just comes down the catching the right exception. As you see above the list is quite long already. However, reading the traceback it seems like `sqlalchemy.exc.ProgrammingError` was raised.

**Comment by Stannislav** [comment]
Cool, I guess it should be straightforward to fix now.

I'm surprised there's no generic way in sqlalchemy to wait for the DB to finish initialising.
