### ISSUE TITLE
Proxy causes connection timeouts and makes it impossible to finish setup

### ISSUE THREAD

**Issue by Only-a-User** [BlueBrain/Search#549]
Hi,

So my problem is, that whenever I try to build a docker image with the base.Dockerfile, it will get to line 62 and from there on I first get this warning: 
```bash
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to bbpproxy.epfl.ch:80 (192.33.211.28), connection timed out
```
 for each package and then this error for each package:
```bash
E: Unable to locate package libbluetooth-dev
```

I had problems with the proxy before, but I could work around those issues. I think this might not be possible here.

Help would be greatly appreciated.

**Comment by Stannislav** [comment]
Hi @Only-a-User, thanks for your interest in `bluesearch`.

The HTTP proxy is only relevant for interal use at Blue Brain. In your case just don't set any HTTP proxy by skipping these two lines
```sh
export http_proxy=http://bbpproxy.epfl.ch:80/
export https_proxy=http://bbpproxy.epfl.ch:80/
```

It could be that this will also make the second issue related to `libbluetooth-dev` go away.

**Comment by Only-a-User** [comment]
@Stannislav thank you for your help!
