### ISSUE TITLE
Compare Huggingface vs. SpaCy performance on NER

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#602]
## Actions
- [ ] Run Huggingface Transformer NER model training on DGX1 on CPU and on GPU. What is the speedup that we get? How do these runtimes compare with what we get when training the NER model using SpaCy (also on CPU and GPU)?
- [ ] Compute NER curves for Huggingface Transformer, and compare them with what we got in #601 for SpaCy.
- [ ] Based on the results (runtime + learning curves) decide whether in the future we should use Huggingface or SpaCy to train our NER models.

## Dependencies
- Requires #601, #603

**Comment by jankrepl** [comment]
Let me just describe both of the models

* SpaCy model: Vanilla NER model not using transformers. The `config.cfg` generated automatically via `prodigy data-to-spacy`
* HF model: Using the following pretrained model https://huggingface.co/dmis-lab/biobert-v1.1 and putting a token classifier on top of it.

Also, the below numbers always refer to the newest (as of writing this post) dataset containing 339 articles.

> Run Huggingface Transformer NER model training on DGX1 on CPU and on GPU. What is the speedup that we get? How do these runtimes compare with what we get when training the NER model using SpaCy (also on CPU and GPU)?

Regarding the setup:
The SpaCy model training seems to be only running on a single CPU and that is what we used.
The HF Trainer automatically detects and uses all available GPU and that is what we used.

The exact runtimes depend on how exactly the early stopping  + other parameters (e.g. evaluation frequency) but both HF and SpaCy train under 5 mins. IMO the training time is negligible in both cases assuming we only want to train once.

> Compute NER curves for Huggingface Transformer, and compare them with what we got in https://github.com/BlueBrain/Search/issues/601 for SpaCy.

Assuming no mistakes, HF is clearly better than SpaCy
![hf_vs_spacy](https://user-images.githubusercontent.com/18519371/175938817-71f2e1ab-6b10-4fed-b861-ee0d4d4c21c6.png)

>  Based on the results (runtime + learning curves) decide whether in the future we should use Huggingface or SpaCy to train our NER models.

One thing to consider here is that to use HF transformer model and get results on SpaCy tokens there is need for additional token alignment logic which requires custom code. It is necessary both at train and inference time. If we don't mind this extra complexity then I would definitely go for HF.

**Comment by EmilieDel** [comment]
Here are the results comparing:
- SpaCy model: Vanilla NER model not using transformers. The config.cfg generated automatically via prodigy data-to-spacy -> referred as `spacy`
- SpaCy model using `biobert_v1.1` transformers backbone. The config.cfg was taken directly from `Search/data_and_models/pipelines/ner/config.cfg` -> referred as `spacy_hf`
- HF model: Using the following pretrained model https://huggingface.co/dmis-lab/biobert-v1.1 and putting a token classifier on top of it. -> referred as `hf`

![image](https://user-images.githubusercontent.com/47669575/177108489-d42c57a2-f9e3-42af-9c0a-e4830a0816d2.png)

**Comment by FrancescoCasalegno** [comment]
## 2022-07-05 Discussion

Based on present results:
- `spacy-tok2vec` seems to be in all cases worse than the other two models
- `spacy-transformer` seems to be more or less equivalent to `huggingface`
