### ISSUE TITLE
Try improving NER model performance by leveraging ontotology-generated text

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#605]
## Context
- DKE has generated texts from the `BRAIN_REGION` ontology and Wikipedia. These sentences also come with annotations which should give us information on the entity type.
- It is desirable that our NLP models become "ontology aware". We can do like the authors of [KELM](https://ai.googleblog.com/2021/05/kelm-integrating-knowledge-graphs-with.html) and enrich our training data with these texts generated from the ontology, so that the resulting NLP model will (hopefully) learn some of the information contained in the ontology.
- We have two possibilities.
  1. Pre-train the backbone on a (self-supervised) Language Model task using a literature database enriched by the generated texts[^1].
  2. Train the head on a (supervised) NER task using the set of training samples annotated by an expert enriched by the generated texts[^2].

## Actions
- [ ] Since we have entity type annotations, it makes sense to try approach 2., as shown in the example below. Compare the performance curves using this enriched training set with what we obtain w/o enriching the training set with these generated sentences.
    <img src="https://user-images.githubusercontent.com/17013890/175168166-c0536007-45cd-465b-84fe-6645f25f2af4.png" width="700px">
- [ ] The generated sentences are about `BRAIN_REGION` but they may contain also mentions of other entity types. We can detect those entities either using our NER model or by human inspection. Are these other entities also annotated or not? Are there many of them?
- [ ] If the generated sentences include many entities of other types w/o annotations, or even just for the fact that we enrich our training set with many sentences that are unbalanced (i.e. exclusively focussing on `BRAIN_REGION`), we may worsen the performance of the NER model on the other entity types. Is this really the case? Is at least the performance for `BRAIN_REGION` any better?
- [ ] Based on these results, decide whether using ontology-generated sentences can help us. If Yes, then ask DKE to generate also for the other entity types.

## Dependencies
- Requires #604 

[^1]: This is the approach described in [KELM](https://ai.googleblog.com/2021/05/kelm-integrating-knowledge-graphs-with.html) paper.
[^2]: Unlike what described in  [KELM](https://ai.googleblog.com/2021/05/kelm-integrating-knowledge-graphs-with.html) paper, we can take this approach because our generated sentences come with annotations on the entity types.

**Comment by EmilieDel** [comment]
Here are the results of the first experiment using the ontology to improve NER model performance. 

### Context

- Spacy model (using default `config.cfg`) is used
- Same splits train/validation/test split is used along the different experiments
     - 220/54/65 if the ontology is not integrated
     - 1681/54/65 if the ontology is added into the training set
- Different experiments are:
    - `Ontology - Full`: Training with addition of ontology sentences (entire `synthetic_text.json`)
    - `Ontology - One Sentence`: Training with addition of ontology sentences (only the first sentence of every paragraph found in the `synthetic_text.json`
    - `No Ontology`: Training without any addition of ontology sentences into the training

#### F1-score
![image](https://user-images.githubusercontent.com/47669575/176627906-fd04a353-9f32-4ff7-baf5-73b6e5bbf229.png)
#### Recall
![image](https://user-images.githubusercontent.com/47669575/176630540-cca04bd9-7f2b-48b7-b9ce-f48c84fa5d6b.png)
#### Precision
![image](https://user-images.githubusercontent.com/47669575/176630631-b2e2bf0f-7de5-4d96-9524-cb25d704d4b6.png)

### Analysis

Currently, the trends are:
- The addition of ontology is not helping the `BRAIN_REGION` entity type that we try to enrich. It is also important to notice that both precision and recall dropped. 
- The addition of ontology sentences is making the results for the other entity types slightly worse but not significantly (except for `CELL_COMPARTMENT` where performance dropped). 

#### Ontology analysis
![image](https://user-images.githubusercontent.com/47669575/176630998-ac0a41d2-b447-42db-8982-3c1ba5a99134.png)
![image](https://user-images.githubusercontent.com/47669575/176631148-5498eba1-6661-4bd8-95d4-a1cc25751a7a.png)

Here are some interrogations I have after looking closer to this ontology sentences:
- Does it make sense to have those entire paragraph showing always the same entity and keeping the same structure. Shouldn't we at least split the sentences into different samples? 
- I am wondering if those entities are really realistic (e.g. `Midbrain, behavioral state related`, `Visceral area, layer XX`, `Cortical amygdalar area, posterior part, lateral zone, layers 1-2`, ...). Do them appear in papers as referred in the ontology? Shouldn't we at least remove the text after the first comma appearing in the entity?
- (Low occurrence) Why do we have part of the first sentence that is not annotated at all in the second image?
- To answer one of the interrogation of this ticket (`The generated sentences are about BRAIN_REGION but they may contain also mentions of other entity types.`), I don't think `synthetic_text.json` contains some entities from the other entity type of interest.

**Comment by EmilieDel** [comment]
One of the problem seems to be that sometimes the first part of the sentence is annotated as a BRAIN REGION
![image](https://user-images.githubusercontent.com/47669575/176851776-d6c3b3d2-e168-48ff-9681-7657949128f0.png)

**Comment by EmilieDel** [comment]
`wiki_text.json` (second source given by DKE) seems not helping either. 
![image](https://user-images.githubusercontent.com/47669575/176922276-0cdbbc19-12e2-48a6-b23b-f86910bf2df1.png)
![image](https://user-images.githubusercontent.com/47669575/176922541-85fb6765-300a-4520-b1f5-074b4668a38b.png)
Questions: are all the brain regions well annotated on those texts ?

**Comment by EmilieDel** [comment]
- Sentences from Allen Brain ontology seems not to be enough realistic to improve the performances of the model (too much entities - very dense, not realistic entities (`XXX, dorsal part, layer XX`), ...
- Wiki texts are a bit better but it feels like a lot of annotations are missing.
