### ISSUE TITLE
Perform Error Analysis of NER model predictions

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#607]
## Context

- In #601 and #602 we saw that our NER model still produces signficant errors in terms of `f1-score`.
- For instance, both `CELL_TYPE` and `CELL_COMPARTMENT` have `f1-score < 0.60`. 
- Before we try to collect more annotated samples, we should inspect the mispredictions through Error Analysis.
- It may be useful to have a look into [`bluesearch.mining.eval.ner_errors()`](https://github.com/BlueBrain/Search/blob/338d6a7dcd1dee413d90d78cf28a28d7442323d7/src/bluesearch/mining/eval.py#L503), which  produces reports of False Positive and False Negative errors found in the evaluation.

## Actions 
- [x] Analyse the errors produced by our NER.
- [x] Are the discrepancies between `y_true` and `y_pred` actual errors or are there mainly subjective differencies (e.g. whether `"cell"` is a `CELL_TYPE`)? 
- [x] What causes `CELL_TYPE` and `CELL_COMPARTMENT` in particular to have such bad `f1-score`?

**Comment by jankrepl** [comment]
Maybe we should write some check to make sure that once an expert annotates a given word to be a specific entity type then each time this word occurs it will be exactly of the same entity type.

Of course, some words might have multiple meanings (lab mouse, Micky Mouse) but we don't have to worry about it IMO since the context is always very narrow.

**Comment by EmilieDel** [comment]
Ideas to improve annotations:
- [ ] Create entity ruler with the annotations and check that all the occurences are annotated - then double check the results manually + out of sample predictions

**Comment by FrancescoCasalegno** [comment]
## 2022-08-26 Planning
- [ ] **Track** with `DVC` current NER annotations (= original annotations from expert).
- [ ] Use **regex** to check that occurrences are consistent, i.e. that if `"mice"` is annotated once as `ORGANISM` it is always annotated as such. If inconsistencies are found, double check by hand and **fix the original annotations** whenever needed. This will help reducing the False Neg in our evaluation.
- [ ] Use k-Fold **out-of-sample predictions** followed by manual verification (with the help of Google/Wikipedia) to see where our model predictions differ from the human annotations, and accordingly **fix the original annotations**. This will help reducing False Pos and False Neg in our evaluation.

**Comment by EmilieDel** [comment]
### Experiment
The idea was to take all the entities annotated by GK and create an entity ruler with all those entities (using a `lemmatizer` to detect `mouse` and `mice`). Once this entity ruler is constructed, the model created is used to predict again on all the annotations. A comparison is done between the GK annotations and the entity ruler predictions.

What was done ?
- Several models (`en_core_web_sm` and `en_core_sci_lg`) - meaning different tokenizer and lemmatizer - were used.
- Conflicts of entity types for the same entity (=lemma) are manually solved (to avoid any randomness in the results). However, this is not scalable.

### Results
The results exposed here are created with `en_core_web_sm` model instantiated the following way
```
nlp = spacy.load("en_core_web_sm", disable=["ner"])
nlp.remove_pipe("lemmatizer")
nlp.add_pipe("lemmatizer", config={"mode": "lookup"}).initialize()
```

- 914 different patterns are detected (and there was 2014 duplicates (=several times the same lemma)
```
GENE                529
CELL_TYPE           156
BRAIN_REGION        138
CELL_COMPARTMENT     46
ORGANISM             45
```
- The comparison between GK annotations and the entity ruler predictions (on all the paragraphs annotated)

| | precision  |  recall  | f1-score  | support |
| -- | -- | -- | -- | -- | 
| BRAIN_REGION  |    0.74   |   0.97 |     0.84    |   345 |
| CELL_COMPARTMENT  |    0.58   |   0.94   |   0.72    |   177 |
| CELL_TYPE   |   0.48 | 0.86 | 0.62 | 677 |
| GENE  |  0.87  | 0.99  | 0.93 | 1469 |
| ORGANISM  | 0.61 | 0.98 | 0.75 | 279 |
- Here are some results:

![image](https://user-images.githubusercontent.com/47669575/181713682-cb43139d-d45d-4701-803c-4f9f7539422c.png)

![image](https://user-images.githubusercontent.com/47669575/181713658-caf580bd-d69c-4334-b833-1d5fb9443424.png)

- Also some false positives are appearing using this method.
![image](https://user-images.githubusercontent.com/47669575/181713628-412cb59d-d013-4218-8f68-c99846e0b100.png)

**Comment by EmilieDel** [comment]
Here are the results of:
- Spacy model trained on the annotations from GK
- Spacy model trained on the entity ruler annotations
The models are evaluated respectively against the annotations from GK and the entity ruler annotations. The train and test splits are kept the same.

![image](https://user-images.githubusercontent.com/47669575/182406697-e5b6a259-2fee-4715-ac6f-8982992f4609.png)
![image](https://user-images.githubusercontent.com/47669575/182406581-95a43389-9b06-43ea-a1a6-20fff13c44a2.png)
![image](https://user-images.githubusercontent.com/47669575/182406651-04b54ed1-b086-41c8-a5f2-0298a005a514.png)

**Comment by FrancescoCasalegno** [comment]
@EmilieDel Awesome, so test score seems to improve signficantly!
Just one thing – after #602 didn't we decide to switch to 🤗 transformers rather than spaCy? Is it possible to see those results?

**Comment by FrancescoCasalegno** [comment]
## Planning 2022-08-02

- [ ] Find out how to export corrected annotations in a format compatible with the one of `prodigy`.
- [ ] Save with `dvc` (put remote on `gpfs`) original annotations + after entity ruler + after entity ruler and manual correction.
- [ ] Re-train and evaluate model (k-fold cross-validation) before/after correction. Also inspect which errors are now made (like https://github.com/BlueBrain/Search/issues/607#issuecomment-1181838460)

**Comment by FrancescoCasalegno** [comment]
See plot in https://github.com/BlueBrain/Search/issues/608#issuecomment-1214915372
