### ISSUE TITLE
Investigate options for storing literature documents

### ISSUE THREAD

**Issue by FrancescoCasalegno** [BlueBrain/Search#609]
## Current Approach
<img src="https://user-images.githubusercontent.com/17013890/178491381-263675a6-3559-45e1-a7b7-73ca7cf09684.png" width="600px">

Currently, this is how we handle queries, see Figure.
1. A query may contain exact match parts — e.g. `"Purkinje cells"` in the query `Resting potential of "Purkinje cells"`.
2. The exact match part of the query is run as a [`FULLTEXT` search](https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html) against a SQL database containing all sentences of all documents, to filter only matching sentences. 
3. IDs of matching sentences are retrieved. Thus, a `torch.Tensor` (which loads embeddings from disk in `hdf5`) is sliced and `torch`'s [`cosine_similarity`](https://pytorch.org/docs/stable/generated/torch.nn.functional.cosine_similarity.html) is used to find the sentences having embedding vectors most similar to the query embedding vector.

## Limitations of Current Approach
1. We are loading all sentence embeddings (generated with [`sentence-transformers`](https://github.com/UKPLab/sentence-transformers)) in memory to compute `cosine_similarity` with `torch`. However, each embedding vector takes `3 kB`[^1] so  it's easy to consume several GB of memory and we may even get out of memory.[^2] So this approach is clearly not scalable. Dedicated frameworks like [`FAISS`](https://github.com/facebookresearch/faiss) allow to perform efficient similarity search of embedding vectors also without need of loading all data in memory.
2. For exact matches, we are storing each sentence in a SQL table in a `TEXT ` column and then running `FULLTEXT` queries. But this seems also not very effective and scalable: dedicated frameworks like [`Elasticsearch`](https://www.elastic.co/what-is/elasticsearch) seems to be the go-to solution for scalable text search applications.

## Actions
- [x] Is `Elasticsearch` an efficient solution for both fulltext searches _and_ database storage?
Or should we use `MongoDB` as database storage and then use `Elasticsearch` to run our text searches?
- [x] `Elasticsearch` [now supports](https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch) information retrieval based on embedding vectors similarity. But there are also dedicated libraries for fast vector search like [FAISS](https://github.com/facebookresearch/faiss), which [may be much faster](https://medium.com/analytics-vidhya/leaping-into-semantic-neural-search-with-elasticsearch-faiss-using-haystack-a198c31ea07b).
Should we use `Elasticsearch` or `FAISS` for our semantic search?
If we use `FAISS`, how can we integrate it with `Elasticsearch`?
In general, how can we combine the results of the "exact match" (based on fulltext search) part of the query with the results of the "semantic search" (based on vector similarity)?
- [x] How can [`Haystack`](https://haystack.deepset.ai/overview/intro) fit in this picture?
- [x] Putting all pieces together, how can we design the new architecture of our Information Retrieval system (including document storage) including all required tools and their mutual integration/relation (e.g. `Elasticsearch`, `FAISS`, `Haystack`)?

[^1]:  Transformers generate embedding vectors with `768` elements, times  `4 B` which is the size of `float`: `4 * 768 B = 3072 B = 3 kiB`.
[^2]: As an example, `CORD19-v65` had `34,6125` articles (some full text, some only abstract) for a total of `26,359,684` sentences. So the total size is `26,359,684 * 3 kB = 80 GiB`!

**Comment by drsantos89** [comment]
https://epflch-my.sharepoint.com/personal/diogo_reissantos_epfl_ch/Documents/database_search.pptx?web=1

**Comment by drsantos89** [comment]
Elasticsearch will be used as a database and full-text and semantic search engine.
MongoDB might be added in the future if ES is not reliable enough.
FAISS might be added in the future if the semantic search is not fast enough on ES.
Solr is a complete open-source alternative to ES.
