### ISSUE TITLE
Remove Python 3.7 from the CI

### ISSUE THREAD

**Issue by jankrepl** [BlueBrain/Search#636]
Mainly because it seems like we can have up to 5 parallel runners at a time. Unfortunately, we have 2 OS and 3 Python versions (=6 runners) currently. This results in ~10 minutes of extra waiting time for the CI.

**Comment by FrancescoCasalegno** [comment]
## Planning 2022-09-27
### Discussion
- BBP has policies on the minimal Python version to be supported, see [**here**](https://bbpteam.epfl.ch/project/spaces/display/BSD/Python+Support+by+BBP+Software).
- Based on such policies, we must support at least from **Python 3.8**.
- Possibly out of scope for this PR, but related: the current active version (see [**here**](https://en.wikipedia.org/wiki/History_of_Python)) is **Python 3.10** so we should start testing for it.
- The current issue (long runtime) seems to be cause by the fact that we are testing `N` python versions by `M=2` operating systems and if `N > 2` we get `N*M > 5` which is the max parallel runners we have. What about dropping CI for Mac OS at least for some versions?

### Actions
- [ ] Drop Python 3.7 from CI.
- [ ] Add Python 3.10 to CI.
- [ ] Only test latest Python version (currently: Python 3.10) both on Mac OS and Ubuntu, other versions to be tested only on Ubuntu.
